/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.mygymmanagementsystem.view;

import lk.ijse.mygymmanagement.view.panel.ReportForPanel;
import lk.ijse.mygymmanagement.view.panel.AttendancePanel;
import lk.ijse.mygymmanagement.view.panel.PaymentPanel;
import lk.ijse.mygymmanagement.view.panel.MesurementPanel;
import lk.ijse.mygymmanagement.view.panel.SchedulePanel;
import lk.ijse.mygymmanagement.view.panel.SettingPanel;
import lk.ijse.mygymmanagement.view.panel.HomePanel;
import lk.ijse.mygymmanagement.view.panel.RegMemberPanel;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JPanel;
import javax.swing.Timer;
import javax.swing.border.LineBorder;
import lk.ijse.mygymmanagementsystem.commmon.IDGenarator;

/**
 *
 * @author Chinthaka
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        // lblA.setBackground(new Color(0,0,0,0f));
        labelVisibleFalse();
        setLocationRelativeTo(null);
        loadHomePanel();
        setDate();
        setTime();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblMember = new javax.swing.JLabel();
        lblSetting = new javax.swing.JLabel();
        lblHome = new javax.swing.JLabel();
        lblAttendance = new javax.swing.JLabel();
        lblPayment = new javax.swing.JLabel();
        lblReport = new javax.swing.JLabel();
        g = new javax.swing.JLabel();
        a = new javax.swing.JLabel();
        b = new javax.swing.JLabel();
        c = new javax.swing.JLabel();
        d = new javax.swing.JLabel();
        e = new javax.swing.JLabel();
        f = new javax.swing.JLabel();
        h = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        panelMain = new javax.swing.JPanel();
        lblMeasurement = new javax.swing.JLabel();
        lblSchedule = new javax.swing.JLabel();
        lblDashboard = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setPreferredSize(new java.awt.Dimension(1350, 760));
        jPanel1.setLayout(null);

        lblMember.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        lblMember.setForeground(new java.awt.Color(255, 255, 255));
        lblMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/Member.png"))); // NOI18N
        lblMember.setText("MEMBER");
        lblMember.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        lblMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMemberMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMemberMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMemberMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMemberMouseClicked(evt);
            }
        });
        jPanel1.add(lblMember);
        lblMember.setBounds(60, 210, 250, 50);

        lblSetting.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        lblSetting.setForeground(new java.awt.Color(255, 255, 255));
        lblSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/setting.png"))); // NOI18N
        lblSetting.setText("SETTINGS");
        lblSetting.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        lblSetting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSettingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSettingMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSettingMousePressed(evt);
            }
        });
        jPanel1.add(lblSetting);
        lblSetting.setBounds(60, 630, 250, 50);

        lblHome.setDisplayedMnemonic('H');
        lblHome.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        lblHome.setForeground(new java.awt.Color(255, 255, 255));
        lblHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/home-1.png"))); // NOI18N
        lblHome.setText("HOME");
        lblHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHomeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblHomeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblHomeMouseReleased(evt);
            }
        });
        jPanel1.add(lblHome);
        lblHome.setBounds(60, 140, 250, 50);

        lblAttendance.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        lblAttendance.setForeground(new java.awt.Color(255, 255, 255));
        lblAttendance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/attendence.png"))); // NOI18N
        lblAttendance.setText("ATTENDANCE");
        lblAttendance.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        lblAttendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAttendanceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAttendanceMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAttendanceMouseClicked(evt);
            }
        });
        jPanel1.add(lblAttendance);
        lblAttendance.setBounds(60, 280, 250, 50);

        lblPayment.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        lblPayment.setForeground(new java.awt.Color(255, 255, 255));
        lblPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/payment-1.png"))); // NOI18N
        lblPayment.setText("PAYMENT");
        lblPayment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        lblPayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPaymentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPaymentMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPaymentMouseClicked(evt);
            }
        });
        jPanel1.add(lblPayment);
        lblPayment.setBounds(60, 490, 250, 50);

        lblReport.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        lblReport.setForeground(new java.awt.Color(255, 255, 255));
        lblReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/report-1.png"))); // NOI18N
        lblReport.setText("REPORTS");
        lblReport.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        lblReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblReportMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReportMouseClicked(evt);
            }
        });
        jPanel1.add(lblReport);
        lblReport.setBounds(60, 560, 250, 50);

        g.setBackground(new java.awt.Color(255, 153, 51));
        g.setOpaque(true);
        jPanel1.add(g);
        g.setBounds(310, 560, 30, 50);

        a.setBackground(new java.awt.Color(255, 153, 51));
        a.setOpaque(true);
        jPanel1.add(a);
        a.setBounds(310, 140, 30, 50);

        b.setBackground(new java.awt.Color(255, 153, 51));
        b.setOpaque(true);
        jPanel1.add(b);
        b.setBounds(310, 210, 30, 50);

        c.setBackground(new java.awt.Color(255, 153, 51));
        c.setOpaque(true);
        jPanel1.add(c);
        c.setBounds(310, 280, 30, 50);

        d.setBackground(new java.awt.Color(255, 153, 51));
        d.setOpaque(true);
        jPanel1.add(d);
        d.setBounds(310, 350, 30, 50);

        e.setBackground(new java.awt.Color(255, 153, 51));
        e.setOpaque(true);
        jPanel1.add(e);
        e.setBounds(310, 420, 30, 50);

        f.setBackground(new java.awt.Color(255, 153, 51));
        f.setOpaque(true);
        jPanel1.add(f);
        f.setBounds(310, 490, 30, 50);

        h.setBackground(new java.awt.Color(255, 153, 51));
        h.setOpaque(true);
        jPanel1.add(h);
        h.setBounds(310, 630, 30, 50);

        lblTime.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        lblTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTime.setText("Time");
        lblTime.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(lblTime);
        lblTime.setBounds(140, 10, 100, 20);

        lblDate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDate.setText("Date");
        lblDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(lblDate);
        lblDate.setBounds(10, 10, 100, 20);

        panelMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 3));
        panelMain.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelMain.setOpaque(false);

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 964, Short.MAX_VALUE)
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 564, Short.MAX_VALUE)
        );

        jPanel1.add(panelMain);
        panelMain.setBounds(340, 120, 970, 570);

        lblMeasurement.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        lblMeasurement.setForeground(new java.awt.Color(255, 255, 255));
        lblMeasurement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/measur.png"))); // NOI18N
        lblMeasurement.setText("MEASUREMENT");
        lblMeasurement.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        lblMeasurement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMeasurementMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMeasurementMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMeasurementMouseClicked(evt);
            }
        });
        jPanel1.add(lblMeasurement);
        lblMeasurement.setBounds(60, 420, 250, 50);

        lblSchedule.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        lblSchedule.setForeground(new java.awt.Color(255, 255, 255));
        lblSchedule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/schedule_1.png"))); // NOI18N
        lblSchedule.setText("SCHEDULE");
        lblSchedule.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        lblSchedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblScheduleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblScheduleMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblScheduleMouseClicked(evt);
            }
        });
        jPanel1.add(lblSchedule);
        lblSchedule.setBounds(60, 350, 250, 50);

        lblDashboard.setText("jLabel2");
        lblDashboard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(lblDashboard);
        lblDashboard.setBounds(30, 120, 300, 570);
        lblDashboard.getAccessibleContext().setAccessibleDescription("");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/02-2.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(1060, 0, 120, 120);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 51));
        jLabel3.setText("MUSCLE HUT Body Building & Fitness");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(750, 20, 260, 20);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 51));
        jLabel4.setText("No: 217, Nalagasdeniya, Baddegama Rd, Hikkaduwa.");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(750, 40, 330, 20);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 51));
        jLabel5.setText("Tel : 0782489971");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(750, 60, 170, 20);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 51));
        jLabel6.setText("E-mail : musclehut@gmail.com");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(750, 80, 310, 20);

        lblMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/Minimize.png"))); // NOI18N
        lblMinimize.setToolTipText("Minimize");
        lblMinimize.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
        });
        jPanel1.add(lblMinimize);
        lblMinimize.setBounds(1270, 10, 32, 32);

        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/close.png"))); // NOI18N
        lblClose.setToolTipText("Close");
        lblClose.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });
        jPanel1.add(lblClose);
        lblClose.setBounds(1310, 10, 32, 32);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/aa.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1350, 760);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMemberMouseClicked
        a.setVisible(false);
        b.setVisible(true);
        c.setVisible(false);
        d.setVisible(false);
        e.setVisible(false);
        f.setVisible(false);
        g.setVisible(false);
        h.setVisible(false);

        panelMain.removeAll();
        RegMemberPanel regMemberPanel = new RegMemberPanel();
        regMemberPanel.setVisible(true);
        regMemberPanel.setSize(panelMain.getSize());
        panelMain.add(regMemberPanel);
        panelMain.repaint();
        panelMain.revalidate();
    }//GEN-LAST:event_lblMemberMouseClicked

    private void lblMemberMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMemberMousePressed

    }//GEN-LAST:event_lblMemberMousePressed

    private void lblSettingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSettingMousePressed
        panelMain.removeAll();
        SettingPanel s1 = new SettingPanel();
        s1.setVisible(true);
        s1.setSize(panelMain.getSize());
        panelMain.add(s1);
        panelMain.repaint();
        panelMain.revalidate();

        a.setVisible(false);
        b.setVisible(false);
        c.setVisible(false);
        d.setVisible(false);
        e.setVisible(false);
        f.setVisible(false);
        g.setVisible(false);
        h.setVisible(true);
    }//GEN-LAST:event_lblSettingMousePressed

    private void lblHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseEntered
        lblHome.setBorder(new LineBorder(new Color(255, 153, 51), 2));
        lblHome.setForeground(new Color(255, 153, 51));
    }//GEN-LAST:event_lblHomeMouseEntered

    private void lblHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseExited
        lblHome.setBorder(new LineBorder(new Color(255, 153, 51), 2));
        lblHome.setForeground(new Color(255, 153, 51));
        
        
    }//GEN-LAST:event_lblHomeMouseExited

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked
        panelMain.removeAll();
        HomePanel homePanel = new HomePanel();
        homePanel.setVisible(true);
        homePanel.setSize(panelMain.getSize());
        panelMain.add(homePanel);
        panelMain.repaint();
        panelMain.revalidate();

        b.setVisible(false);
        a.setVisible(true);
        c.setVisible(false);
        d.setVisible(false);
        e.setVisible(false);
        f.setVisible(false);
        g.setVisible(false);
        h.setVisible(false);
    }//GEN-LAST:event_lblHomeMouseClicked

    private void lblHomeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseReleased
        
    }//GEN-LAST:event_lblHomeMouseReleased

    private void lblMemberMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMemberMouseEntered
        lblMember.setBorder(new LineBorder(new Color(255, 153, 51), 2));
        lblMember.setForeground(new Color(255, 153, 51));
    }//GEN-LAST:event_lblMemberMouseEntered

    private void lblMemberMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMemberMouseExited
        lblMember.setBorder(new LineBorder(Color.WHITE, 2));
        lblMember.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblMemberMouseExited

    private void lblAttendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAttendanceMouseClicked
        a.setVisible(false);
        b.setVisible(false);
        c.setVisible(true);
        d.setVisible(false);
        e.setVisible(false);
        f.setVisible(false);
        g.setVisible(false);
        h.setVisible(false);

        panelMain.removeAll();
        AttendancePanel attendancePanel = new AttendancePanel();
        attendancePanel.setVisible(true);
        attendancePanel.setSize(panelMain.getSize());
        panelMain.add(attendancePanel);
        panelMain.repaint();
        panelMain.revalidate();
    }//GEN-LAST:event_lblAttendanceMouseClicked

    private void lblAttendanceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAttendanceMouseEntered
        lblAttendance.setBorder(new LineBorder(new Color(255, 153, 51), 2));
        lblAttendance.setForeground(new Color(255, 153, 51));
    }//GEN-LAST:event_lblAttendanceMouseEntered

    private void lblAttendanceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAttendanceMouseExited
        lblAttendance.setBorder(new LineBorder(Color.WHITE, 2));
        lblAttendance.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblAttendanceMouseExited

    private void lblPaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPaymentMouseClicked
        a.setVisible(false);
        b.setVisible(false);
        c.setVisible(false);
        d.setVisible(false);
        e.setVisible(false);
        f.setVisible(true);
        g.setVisible(false);
        h.setVisible(false);

        panelMain.removeAll();
        PaymentPanel paymentPanel = new PaymentPanel();
        paymentPanel.setVisible(true);
        paymentPanel.setSize(panelMain.getSize());
        panelMain.add(paymentPanel);
        panelMain.repaint();
        panelMain.revalidate();
    }//GEN-LAST:event_lblPaymentMouseClicked

    private void lblPaymentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPaymentMouseEntered
        lblPayment.setBorder(new LineBorder(new Color(255, 153, 51), 2));
        lblPayment.setForeground(new Color(255, 153, 51));
    }//GEN-LAST:event_lblPaymentMouseEntered

    private void lblPaymentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPaymentMouseExited
        lblPayment.setBorder(new LineBorder(Color.WHITE, 2));
        lblPayment.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblPaymentMouseExited

    private void lblScheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblScheduleMouseClicked
        a.setVisible(false);
        b.setVisible(false);
        c.setVisible(false);
        d.setVisible(true);
        e.setVisible(false);
        f.setVisible(false);
        g.setVisible(false);
        h.setVisible(false);
        
        panelMain.removeAll();
        SchedulePanel schedulePanel = new SchedulePanel();
        schedulePanel.setVisible(true);
        schedulePanel.setSize(panelMain.getSize());
        panelMain.add(schedulePanel);
        panelMain.repaint();
        panelMain.revalidate();
    }//GEN-LAST:event_lblScheduleMouseClicked

    private void lblScheduleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblScheduleMouseEntered
        lblSchedule.setBorder(new LineBorder(new Color(255, 153, 51), 2));
        lblSchedule.setForeground(new Color(255, 153, 51));
    }//GEN-LAST:event_lblScheduleMouseEntered

    private void lblScheduleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblScheduleMouseExited
        lblSchedule.setBorder(new LineBorder(Color.WHITE, 2));
        lblSchedule.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblScheduleMouseExited

    private void lblReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportMouseClicked
        a.setVisible(false);
        b.setVisible(false);
        c.setVisible(false);
        d.setVisible(false);
        e.setVisible(false);
        f.setVisible(false);
        g.setVisible(true);
        h.setVisible(false);
        
        panelMain.removeAll();
        ReportForPanel reportPanel = new ReportForPanel();
        reportPanel.setVisible(true);
        reportPanel.setSize(panelMain.getSize());
        panelMain.add(reportPanel);
        panelMain.repaint();
        panelMain.revalidate();

       
    }//GEN-LAST:event_lblReportMouseClicked

    private void lblReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportMouseEntered
        lblReport.setBorder(new LineBorder(new Color(255, 153, 51), 2));
        lblReport.setForeground(new Color(255, 153, 51));
    }//GEN-LAST:event_lblReportMouseEntered

    private void lblReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportMouseExited
        lblReport.setBorder(new LineBorder(Color.WHITE, 2));
        lblReport.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblReportMouseExited

    private void lblSettingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSettingMouseEntered
        lblSetting.setBorder(new LineBorder(new Color(255, 153, 51), 2));
        lblSetting.setForeground(new Color(255, 153, 51));
    }//GEN-LAST:event_lblSettingMouseEntered

    private void lblSettingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSettingMouseExited
        lblSetting.setBorder(new LineBorder(Color.WHITE, 2));
        lblSetting.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblSettingMouseExited

    private void lblCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseEntered
        lblClose.setBorder(new LineBorder(new Color(255, 153, 51), 3));
        lblClose.setForeground(new Color(255, 153, 51));
    }//GEN-LAST:event_lblCloseMouseEntered

    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        lblClose.setBorder(new LineBorder(Color.WHITE, 2));
        lblClose.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblCloseMouseExited

    private void lblMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseEntered
        lblMinimize.setBorder(new LineBorder(new Color(255, 153, 51), 3));
        lblMinimize.setForeground(new Color(255, 153, 51));
    }//GEN-LAST:event_lblMinimizeMouseEntered

    private void lblMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseExited
        lblMinimize.setBorder(new LineBorder(Color.WHITE, 2));
        lblMinimize.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblMinimizeMouseExited

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        setExtendedState(HomePage.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void lblMeasurementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMeasurementMouseClicked
        a.setVisible(false);
        b.setVisible(false);
        c.setVisible(false);
        d.setVisible(false);
        e.setVisible(true);
        f.setVisible(false);
        g.setVisible(false);
        h.setVisible(false);
        
        panelMain.removeAll();
        MesurementPanel mesurementPanel = new MesurementPanel();
        mesurementPanel.setVisible(true);
        mesurementPanel.setSize(panelMain.getSize());
        panelMain.add(mesurementPanel);
        panelMain.repaint();
        panelMain.revalidate();
    }//GEN-LAST:event_lblMeasurementMouseClicked

    private void lblMeasurementMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMeasurementMouseEntered
        lblMeasurement.setBorder(new LineBorder(new Color(255, 153, 51), 3));
        lblMeasurement.setForeground(new Color(255, 153, 51));
    }//GEN-LAST:event_lblMeasurementMouseEntered

    private void lblMeasurementMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMeasurementMouseExited
        lblMeasurement.setBorder(new LineBorder(Color.WHITE, 2));
        lblMeasurement.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblMeasurementMouseExited

    private void lblHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMousePressed
        
    }//GEN-LAST:event_lblHomeMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a;
    private javax.swing.JLabel b;
    private javax.swing.JLabel c;
    private javax.swing.JLabel d;
    private javax.swing.JLabel e;
    private javax.swing.JLabel f;
    private javax.swing.JLabel g;
    private javax.swing.JLabel h;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAttendance;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblMeasurement;
    private javax.swing.JLabel lblMember;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblPayment;
    private javax.swing.JLabel lblReport;
    private javax.swing.JLabel lblSchedule;
    private javax.swing.JLabel lblSetting;
    private javax.swing.JLabel lblTime;
    private static javax.swing.JPanel panelMain;
    // End of variables declaration//GEN-END:variables

    private void labelVisibleFalse() {
        a.setVisible(false);
        b.setVisible(false);
        c.setVisible(false);
        d.setVisible(false);
        e.setVisible(false);
        f.setVisible(false);
        g.setVisible(false);
        h.setVisible(false);
    }

    public static JPanel getMainPanel() {
        return panelMain;
    }

    private void loadHomePanel() {
        panelMain.removeAll();
        HomePanel homePanel = new HomePanel();
        homePanel.setVisible(true);
        homePanel.setSize(panelMain.getSize());
        panelMain.add(homePanel);
        panelMain.repaint();
        panelMain.revalidate();
        a.setVisible(true);
    }

    private void setDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        lblDate.setText(s.format(d));
    }

    private void setTime() {
        new Timer(0, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                lblTime.setText(s.format(d));
            }
        }).start();
    }
}
