/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.mygymmanagement.view.panel;

import java.awt.Color;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import lk.ijse.mygymmanagement.controller.AttendanceController;
import lk.ijse.mygymmanagement.controller.ExerciseController;
import lk.ijse.mygymmanagement.controller.ManageInventoryController;
import lk.ijse.mygymmanagement.controller.MemberController;
import lk.ijse.mygymmanagement.controller.RegMemberController;
import lk.ijse.mygymmanagement.controller.ViewAllAttendanceController;
import lk.ijse.mygymmanagementsystem.commmon.IDGenarator;
import lk.ijse.mygymmanagementsystem.core.dto.AttendanceDTO;
import lk.ijse.mygymmanagementsystem.core.dto.ExerciseDTO;
import lk.ijse.mygymmanagementsystem.core.dto.InventoryDTO;
import lk.ijse.mygymmanagementsystem.core.dto.MemeberDTO;
import lk.ijse.mygymmanagementsystem.core.dto.RegistrationDTO;
import lk.ijse.mygymmanagementsystem.core.dto.ViewAllAttendanceDTO;
import lk.ijse.mygymmanagementsystem.view.HomePage;

/**
 *
 * @author Chinthaka
 */
public class AttendancePanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public AttendancePanel() {
        initComponents();
        loadAllMemberRegNo();
        setDate();
        getAttendanceID();
        loadAllAttndance();

        tblAttend.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {

                if (tblAttend.getSelectedRow() == -1) {
                    return;
                }

                String attendId = tblAttend.getValueAt(tblAttend.getSelectedRow(), 0).toString();
                String memberReg = tblAttend.getValueAt(tblAttend.getSelectedRow(), 1).toString();
                String date = tblAttend.getValueAt(tblAttend.getSelectedRow(), 2).toString();
                String intime = tblAttend.getValueAt(tblAttend.getSelectedRow(), 3).toString();
                String outTime = tblAttend.getValueAt(tblAttend.getSelectedRow(), 4).toString();

                txtAttendId.setText(attendId);
                cmbMemberRegNo.setSelectedItem(memberReg);
                txtDate.setText(date);
                txtInTime.setText(intime);
                txtOutTime.setText(outTime);

            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtOutTime = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblSave1 = new javax.swing.JLabel();
        lblNext = new javax.swing.JLabel();
        lblSave = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAttend = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblCount = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        TxtMemberName = new javax.swing.JTextField();
        txtInTime = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtAttendId = new javax.swing.JTextField();
        cmbMemberRegNo = new javax.swing.JComboBox<>();
        txtMemberID = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(970, 570));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Stencil Std", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/attendence.png"))); // NOI18N
        jLabel2.setText("Attendance..");
        add(jLabel2);
        jLabel2.setBounds(10, 10, 240, 50);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText(":");
        add(jLabel14);
        jLabel14.setBounds(130, 530, 20, 22);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Member ID");
        add(jLabel17);
        jLabel17.setBounds(30, 130, 140, 30);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Member Name");
        add(jLabel18);
        jLabel18.setBounds(30, 170, 140, 30);

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText(":");
        add(jLabel29);
        jLabel29.setBounds(170, 170, 20, 30);

        txtOutTime.setBackground(new Color(0,0,0,0f));
        txtOutTime.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtOutTime.setForeground(new java.awt.Color(255, 255, 255));
        txtOutTime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtOutTime.setAutoscrolls(false);
        txtOutTime.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtOutTime.setCaretColor(new java.awt.Color(255, 255, 255));
        txtOutTime.setOpaque(false);
        txtOutTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOutTimeActionPerformed(evt);
            }
        });
        txtOutTime.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtOutTimeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOutTimeKeyReleased(evt);
            }
        });
        add(txtOutTime);
        txtOutTime.setBounds(750, 170, 180, 30);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Member Reg.No");
        add(jLabel19);
        jLabel19.setBounds(30, 90, 140, 30);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText(":");
        add(jLabel15);
        jLabel15.setBounds(170, 90, 20, 30);

        lblSave1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblSave1.setForeground(new java.awt.Color(255, 255, 255));
        lblSave1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSave1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/cancel.png"))); // NOI18N
        lblSave1.setText("Cancel");
        lblSave1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblSave1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSave1MouseClicked(evt);
            }
        });
        add(lblSave1);
        lblSave1.setBounds(670, 520, 140, 40);

        lblNext.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNext.setForeground(new java.awt.Color(255, 255, 255));
        lblNext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/next.png"))); // NOI18N
        lblNext.setText("Next");
        lblNext.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        lblNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNextMouseClicked(evt);
            }
        });
        add(lblNext);
        lblNext.setBounds(830, 520, 110, 40);

        lblSave.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblSave.setForeground(new java.awt.Color(255, 255, 255));
        lblSave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/save.png"))); // NOI18N
        lblSave.setText("Save");
        lblSave.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        lblSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSaveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSaveMouseExited(evt);
            }
        });
        add(lblSave);
        lblSave.setBounds(820, 230, 110, 40);

        tblAttend.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tblAttend.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Attendance ID", "Member Reg.No", "Date", "In-Time", "Out-Time"
            }
        ));
        jScrollPane1.setViewportView(tblAttend);

        add(jScrollPane1);
        jScrollPane1.setBounds(20, 290, 920, 220);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("No of Members");
        add(jLabel3);
        jLabel3.setBounds(30, 530, 100, 20);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText(":");
        add(jLabel16);
        jLabel16.setBounds(170, 130, 20, 30);

        lblCount.setBackground(new Color(0,0,0,0f));
        lblCount.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblCount.setForeground(new java.awt.Color(255, 255, 255));
        lblCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        add(lblCount);
        lblCount.setBounds(150, 530, 60, 20);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Date");
        add(jLabel20);
        jLabel20.setBounds(550, 90, 140, 30);

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText(":");
        add(jLabel30);
        jLabel30.setBounds(710, 90, 20, 30);

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("In-Time");
        add(jLabel21);
        jLabel21.setBounds(550, 130, 140, 30);

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Out-Time");
        add(jLabel22);
        jLabel22.setBounds(550, 170, 140, 30);

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText(":");
        add(jLabel32);
        jLabel32.setBounds(710, 130, 20, 30);

        jLabel33.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText(":");
        add(jLabel33);
        jLabel33.setBounds(710, 170, 20, 30);

        TxtMemberName.setBackground(new Color(0,0,0,0f));
        TxtMemberName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        TxtMemberName.setForeground(new java.awt.Color(255, 255, 255));
        TxtMemberName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtMemberName.setAutoscrolls(false);
        TxtMemberName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        TxtMemberName.setCaretColor(new java.awt.Color(255, 255, 255));
        TxtMemberName.setOpaque(false);
        TxtMemberName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtMemberNameActionPerformed(evt);
            }
        });
        TxtMemberName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtMemberNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtMemberNameKeyReleased(evt);
            }
        });
        add(TxtMemberName);
        TxtMemberName.setBounds(200, 170, 180, 30);

        txtInTime.setBackground(new Color(0,0,0,0f));
        txtInTime.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtInTime.setForeground(new java.awt.Color(255, 255, 255));
        txtInTime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtInTime.setAutoscrolls(false);
        txtInTime.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtInTime.setCaretColor(new java.awt.Color(255, 255, 255));
        txtInTime.setOpaque(false);
        txtInTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInTimeActionPerformed(evt);
            }
        });
        txtInTime.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInTimeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtInTimeKeyReleased(evt);
            }
        });
        add(txtInTime);
        txtInTime.setBounds(750, 130, 180, 30);

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Attendance ID");
        add(jLabel23);
        jLabel23.setBounds(620, 30, 140, 30);

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText(":");
        add(jLabel24);
        jLabel24.setBounds(760, 30, 20, 30);

        txtAttendId.setBackground(new Color(0,0,0,0f));
        txtAttendId.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtAttendId.setForeground(new java.awt.Color(255, 255, 255));
        txtAttendId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAttendId.setAutoscrolls(false);
        txtAttendId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtAttendId.setCaretColor(new java.awt.Color(255, 255, 255));
        txtAttendId.setOpaque(false);
        txtAttendId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAttendIdActionPerformed(evt);
            }
        });
        txtAttendId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAttendIdKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAttendIdKeyReleased(evt);
            }
        });
        add(txtAttendId);
        txtAttendId.setBounds(790, 30, 140, 30);

        cmbMemberRegNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbMemberRegNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        cmbMemberRegNo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbMemberRegNoItemStateChanged(evt);
            }
        });
        cmbMemberRegNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMemberRegNoActionPerformed(evt);
            }
        });
        add(cmbMemberRegNo);
        cmbMemberRegNo.setBounds(200, 90, 180, 30);

        txtMemberID.setBackground(new Color(0,0,0,0f));
        txtMemberID.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtMemberID.setForeground(new java.awt.Color(255, 255, 255));
        txtMemberID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMemberID.setAutoscrolls(false);
        txtMemberID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtMemberID.setCaretColor(new java.awt.Color(255, 255, 255));
        txtMemberID.setOpaque(false);
        txtMemberID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMemberIDActionPerformed(evt);
            }
        });
        txtMemberID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMemberIDKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMemberIDKeyReleased(evt);
            }
        });
        add(txtMemberID);
        txtMemberID.setBounds(200, 130, 180, 30);

        txtDate.setBackground(new Color(0,0,0,0f));
        txtDate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtDate.setForeground(new java.awt.Color(255, 255, 255));
        txtDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDate.setAutoscrolls(false);
        txtDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtDate.setCaretColor(new java.awt.Color(255, 255, 255));
        txtDate.setOpaque(false);
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });
        txtDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDateKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDateKeyReleased(evt);
            }
        });
        add(txtDate);
        txtDate.setBounds(750, 90, 180, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/Untitled-1.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 3));
        add(jLabel1);
        jLabel1.setBounds(0, 0, 970, 570);
    }// </editor-fold>//GEN-END:initComponents

    private void txtOutTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOutTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOutTimeActionPerformed

    private void txtOutTimeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOutTimeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOutTimeKeyPressed

    private void txtOutTimeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOutTimeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOutTimeKeyReleased

    private void TxtMemberNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtMemberNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtMemberNameActionPerformed

    private void TxtMemberNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtMemberNameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtMemberNameKeyPressed

    private void TxtMemberNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtMemberNameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtMemberNameKeyReleased

    private void txtInTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInTimeActionPerformed
        txtOutTime.requestFocus();
    }//GEN-LAST:event_txtInTimeActionPerformed

    private void txtInTimeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInTimeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInTimeKeyPressed

    private void txtInTimeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInTimeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInTimeKeyReleased

    private void txtAttendIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAttendIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAttendIdActionPerformed

    private void txtAttendIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAttendIdKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAttendIdKeyPressed

    private void txtAttendIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAttendIdKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAttendIdKeyReleased

    private void lblSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaveMouseClicked
        try {
            AttendanceDTO attend = new AttendanceDTO(
                    txtAttendId.getText(),
                    cmbMemberRegNo.getSelectedItem().toString(),
                    txtDate.getText(),
                    txtInTime.getText(),
                    txtOutTime.getText());
            boolean result = AttendanceController.addAttendance(attend);

            if (result) {
                JOptionPane.showMessageDialog(this, "Attendance has been successfully Saved.");
                loadAllAttndance();
                getAttendanceID();
                ViewAllAttendanceDTO attend1 = new ViewAllAttendanceDTO(
                        cmbMemberRegNo.getSelectedItem().toString(),
                        txtMemberID.getText(),
                        TxtMemberName.getText(),
                        txtDate.getText());
                boolean result1 = ViewAllAttendanceController.addAttendence(attend1);
            } else {
                JOptionPane.showMessageDialog(this, "Attendance hasn't been Saved due to some error");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        clearAllTextFileds();
        txtAttendId.requestFocus();
    }//GEN-LAST:event_lblSaveMouseClicked

    private void lblSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaveMouseEntered
        lblSave.setSize(140, 50);
    }//GEN-LAST:event_lblSaveMouseEntered

    private void lblSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaveMouseExited
        lblSave.setSize(110, 40);
    }//GEN-LAST:event_lblSaveMouseExited

    private void cmbMemberRegNoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbMemberRegNoItemStateChanged
        try {
            RegistrationDTO registrationDTO = RegMemberController.searchRegistration((String) cmbMemberRegNo.getSelectedItem());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());

        }
        searchMember();
    }//GEN-LAST:event_cmbMemberRegNoItemStateChanged

    private void txtMemberIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMemberIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMemberIDActionPerformed

    private void txtMemberIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMemberIDKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMemberIDKeyPressed

    private void txtMemberIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMemberIDKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMemberIDKeyReleased

    private void cmbMemberRegNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMemberRegNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMemberRegNoActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void txtDateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDateKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateKeyPressed

    private void txtDateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDateKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateKeyReleased

    private void lblSave1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSave1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSave1MouseClicked

    private void lblNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNextMouseClicked
        MemberAttendance memberAttendance = new MemberAttendance();
        JPanel middlePanel = HomePage.getMainPanel();
        middlePanel.removeAll();
        memberAttendance.setSize(middlePanel.getSize());
        middlePanel.add(memberAttendance);
        middlePanel.revalidate();
        middlePanel.repaint();
    }//GEN-LAST:event_lblNextMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtMemberName;
    private javax.swing.JComboBox<String> cmbMemberRegNo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCount;
    private javax.swing.JLabel lblNext;
    private javax.swing.JLabel lblSave;
    private javax.swing.JLabel lblSave1;
    private javax.swing.JTable tblAttend;
    private javax.swing.JTextField txtAttendId;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtInTime;
    private javax.swing.JTextField txtMemberID;
    private javax.swing.JTextField txtOutTime;
    // End of variables declaration//GEN-END:variables

    private void loadAllMemberRegNo() {
        try {
            ArrayList<RegistrationDTO> RList = RegMemberController.getAllRegistration();
            if(RList!=null){
               for (RegistrationDTO registrationDTO : RList) {
                cmbMemberRegNo.addItem(registrationDTO.getMemberRegNo());
            } 
            }
            
        } catch (Exception ex) {
            Logger.getLogger(AttendancePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /*private void loadMemberIDs() {
        try {
            ArrayList<MemeberDTO> RList = MemberController.getAllMember();
            for (MemeberDTO memeberDTO : RList) {
                cmbMemberID.addItem(memeberDTO.getMemberID());
            }
        } catch (Exception ex) {
            Logger.getLogger(AttendancePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }*/
    private void searchMember() {
        String regisID = (String) cmbMemberRegNo.getSelectedItem();
        try {
            RegistrationDTO registrationDTO = RegMemberController.searchRegistration(regisID);
            if (registrationDTO != null) {
                txtMemberID.setText(registrationDTO.getMemberID());
                MemeberDTO dTO = MemberController.searchMember(txtMemberID.getText());
                if (dTO != null) {
                    TxtMemberName.setText(dTO.getMemberName());
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(AttendancePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void clearAllTextFileds() {
       // txtAttendId.setText("");
        cmbMemberRegNo.setSelectedItem(null);
        txtMemberID.setText("");
        TxtMemberName.setText("");
        txtDate.setText("");
        txtInTime.setText("");
        txtOutTime.setText("");
    }

    private void loadAllAttndance() {
        try {
            ArrayList<AttendanceDTO> allAttendance = AttendanceController.getAllAttendance();

            DefaultTableModel dtm = (DefaultTableModel) tblAttend.getModel();

            dtm.setRowCount(0);

            if (allAttendance != null) {

                for (AttendanceDTO attend : allAttendance) {

                    Object[] rowData = {
                        attend.getAttendanceID(),
                        attend.getMemberRegNo(),
                        attend.getDate(),
                        attend.getInTime(),
                        attend.getOutTime()
                    };

                    dtm.addRow(rowData);

                }

            }
            lblCount.setText(Integer.toString(tblAttend.getRowCount()));

        } catch (Exception ex) {
            Logger.getLogger(AttendancePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        txtDate.setText(s.format(d));

    }
    
    private void getAttendanceID() {
        String newID;
        try {
            newID = IDGenarator.getNewID("attendance","Attendance_ID", "Att");
            txtAttendId.setText(newID);

        } catch (SQLException ex) {
            Logger.getLogger(RegMemberPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegMemberPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
