/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.mygymmanagement.view.panel;

import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import lk.ijse.mygymmanagement.controller.ExerciseController;
import lk.ijse.mygymmanagement.controller.ManageInventoryController;
import lk.ijse.mygymmanagementsystem.commmon.IDGenarator;
import lk.ijse.mygymmanagementsystem.core.dto.ExerciseDTO;
import lk.ijse.mygymmanagementsystem.core.dto.InventoryDTO;
import lk.ijse.mygymmanagementsystem.view.HomePage;

/**
 *
 * @author Chinthaka
 */
public class ExercisePanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public ExercisePanel() {
        initComponents();
        getExerciseID();
        loadAllExercise();

        tblExercise.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {

                if (tblExercise.getSelectedRow() == -1) {
                    return;
                }

                String exerciseID = tblExercise.getValueAt(tblExercise.getSelectedRow(), 0).toString();
                String exerciseName = tblExercise.getValueAt(tblExercise.getSelectedRow(), 1).toString();

                txtExerciseID.setText(exerciseID);
                txtExerciseName.setText(exerciseName);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtExerciseName = new javax.swing.JTextField();
        txtExerciseID = new javax.swing.JTextField();
        lblCreateMember = new javax.swing.JLabel();
        lblRemove = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblExercise = new javax.swing.JTable();
        lblSave = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(970, 570));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Stencil Std", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/exercise.png"))); // NOI18N
        jLabel2.setText("exercise..");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 210, 50);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Exercise ID");
        add(jLabel19);
        jLabel19.setBounds(50, 170, 120, 30);

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Exercise Name");
        add(jLabel23);
        jLabel23.setBounds(50, 220, 120, 30);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText(":");
        add(jLabel16);
        jLabel16.setBounds(170, 170, 20, 30);

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText(":");
        add(jLabel29);
        jLabel29.setBounds(170, 220, 20, 30);

        txtExerciseName.setBackground(new Color(0,0,0,0f));
        txtExerciseName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtExerciseName.setForeground(new java.awt.Color(255, 255, 255));
        txtExerciseName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtExerciseName.setAutoscrolls(false);
        txtExerciseName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtExerciseName.setCaretColor(new java.awt.Color(255, 255, 255));
        txtExerciseName.setOpaque(false);
        txtExerciseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExerciseNameActionPerformed(evt);
            }
        });
        txtExerciseName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtExerciseNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtExerciseNameKeyReleased(evt);
            }
        });
        add(txtExerciseName);
        txtExerciseName.setBounds(200, 220, 210, 30);

        txtExerciseID.setBackground(new Color(0,0,0,0f));
        txtExerciseID.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtExerciseID.setForeground(new java.awt.Color(255, 255, 255));
        txtExerciseID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtExerciseID.setAutoscrolls(false);
        txtExerciseID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtExerciseID.setCaretColor(new java.awt.Color(255, 255, 255));
        txtExerciseID.setOpaque(false);
        txtExerciseID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExerciseIDActionPerformed(evt);
            }
        });
        txtExerciseID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtExerciseIDKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtExerciseIDKeyReleased(evt);
            }
        });
        add(txtExerciseID);
        txtExerciseID.setBounds(200, 170, 150, 30);

        lblCreateMember.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblCreateMember.setForeground(new java.awt.Color(255, 255, 255));
        lblCreateMember.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreateMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/add.png"))); // NOI18N
        lblCreateMember.setText("Add New Exercise");
        lblCreateMember.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblCreateMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCreateMemberMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCreateMemberMouseClicked(evt);
            }
        });
        add(lblCreateMember);
        lblCreateMember.setBounds(50, 110, 270, 30);

        lblRemove.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblRemove.setForeground(new java.awt.Color(255, 255, 255));
        lblRemove.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRemove.setText("Remove Exercise");
        lblRemove.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRemoveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRemoveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRemoveMouseExited(evt);
            }
        });
        add(lblRemove);
        lblRemove.setBounds(670, 490, 190, 30);

        tblExercise.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "                          Exercise ID", "                          Exercise Name"
            }
        ));
        jScrollPane1.setViewportView(tblExercise);

        add(jScrollPane1);
        jScrollPane1.setBounds(450, 160, 470, 280);

        lblSave.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblSave.setForeground(new java.awt.Color(255, 255, 255));
        lblSave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/save.png"))); // NOI18N
        lblSave.setText("Save");
        lblSave.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSaveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSaveMouseExited(evt);
            }
        });
        add(lblSave);
        lblSave.setBounds(160, 280, 110, 40);

        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(255, 153, 51), new java.awt.Color(255, 153, 51), new java.awt.Color(255, 153, 51), new java.awt.Color(255, 153, 51)));
        add(jLabel3);
        jLabel3.setBounds(20, 70, 910, 490);

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/back.png"))); // NOI18N
        jLabel21.setText("BACK");
        jLabel21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        add(jLabel21);
        jLabel21.setBounds(840, 10, 120, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/Untitled-1.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 3));
        add(jLabel1);
        jLabel1.setBounds(0, 0, 970, 570);
    }// </editor-fold>//GEN-END:initComponents

    private void txtExerciseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExerciseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExerciseNameActionPerformed

    private void txtExerciseNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtExerciseNameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExerciseNameKeyPressed

    private void txtExerciseNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtExerciseNameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExerciseNameKeyReleased

    private void txtExerciseIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExerciseIDActionPerformed
        txtExerciseName.requestFocus();
    }//GEN-LAST:event_txtExerciseIDActionPerformed

    private void txtExerciseIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtExerciseIDKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExerciseIDKeyPressed

    private void txtExerciseIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtExerciseIDKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExerciseIDKeyReleased

    private void lblCreateMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreateMemberMouseClicked
        clearAllTextFileds();
        getExerciseID();
        txtExerciseName.requestFocusInWindow();
    }//GEN-LAST:event_lblCreateMemberMouseClicked

    private void lblCreateMemberMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreateMemberMousePressed

    }//GEN-LAST:event_lblCreateMemberMousePressed

    private void lblSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaveMouseClicked

        if (txtExerciseName.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Fill Exercise Name");
        } else {
            try {
                ExerciseDTO exercise = new ExerciseDTO(
                        txtExerciseID.getText(),
                        txtExerciseName.getText());
                boolean result = ExerciseController.addExercise(exercise);

                if (result) {
                    JOptionPane.showMessageDialog(this, "Exercise has been successfully Saved.");
                    loadAllExercise();
                    getExerciseID();
                } else {
                    JOptionPane.showMessageDialog(this, "Exercise hasn't been Saved due to some error");
                }
            } catch (Exception ex) {
                Logger.getLogger(ExercisePanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            txtExerciseName.setText("");
            txtExerciseName.requestFocus();
        }
    }//GEN-LAST:event_lblSaveMouseClicked

    private void lblRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRemoveMouseClicked
        ExerciseDTO exercise = new ExerciseDTO(
                txtExerciseID.getText(),
                txtExerciseName.getText());
        try {
            boolean result = ExerciseController.deleteExercise(exercise);

            if (result) {
                JOptionPane.showMessageDialog(this, "Exercise has been successfully deleted.");
                loadAllExercise();
            } else {
                JOptionPane.showMessageDialog(this, "Exercise hasn't been deleted due to some error");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "No Such Exercise");
        }
        clearAllTextFileds();
        
    }//GEN-LAST:event_lblRemoveMouseClicked

    private void lblSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaveMouseEntered
        lblSave.setSize(140, 50);
    }//GEN-LAST:event_lblSaveMouseEntered

    private void lblSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaveMouseExited
        lblSave.setSize(110, 40);
    }//GEN-LAST:event_lblSaveMouseExited

    private void lblRemoveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRemoveMouseEntered
        lblRemove.setSize(210, 40);
    }//GEN-LAST:event_lblRemoveMouseEntered

    private void lblRemoveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRemoveMouseExited
        lblRemove.setSize(190, 30);
    }//GEN-LAST:event_lblRemoveMouseExited

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        HomePanel hp = new HomePanel();
        JPanel middlePanel = HomePage.getMainPanel();
        middlePanel.removeAll();
        hp.setSize(middlePanel.getSize());
        middlePanel.add(hp);
        middlePanel.revalidate();
        middlePanel.repaint();
    }//GEN-LAST:event_jLabel21MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCreateMember;
    private javax.swing.JLabel lblRemove;
    private javax.swing.JLabel lblSave;
    private javax.swing.JTable tblExercise;
    private javax.swing.JTextField txtExerciseID;
    private javax.swing.JTextField txtExerciseName;
    // End of variables declaration//GEN-END:variables

    private void clearAllTextFileds() {
        txtExerciseID.setText("");
        txtExerciseName.setText("");
    }

    private void loadAllExercise() {
        try {
            ArrayList<ExerciseDTO> allExercises = ExerciseController.getAllExercise();

            DefaultTableModel dtm = (DefaultTableModel) tblExercise.getModel();

            dtm.setRowCount(0);

            if (allExercises != null) {

                for (ExerciseDTO exercise : allExercises) {

                    Object[] rowData = {
                        exercise.getExerciseID(),
                        exercise.getExerciseName()
                    };

                    dtm.addRow(rowData);

                }

            }

        } catch (Exception ex) {
            Logger.getLogger(ExercisePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void getExerciseID() {
        String newID;
        try {
            newID = IDGenarator.getNewID("exercise", "Exercise_ID", "Exr");
            txtExerciseID.setText(newID);

        } catch (SQLException ex) {
            Logger.getLogger(RegMemberPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegMemberPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
