/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.mygymmanagement.view.panel;

import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import lk.ijse.mygymmanagement.controller.ManageInstructorController;
import lk.ijse.mygymmanagement.controller.ManageInventoryController;
import lk.ijse.mygymmanagementsystem.commmon.IDGenarator;
import lk.ijse.mygymmanagementsystem.core.dto.InstructorDTO;
import lk.ijse.mygymmanagementsystem.core.dto.InventoryDTO;
import lk.ijse.mygymmanagementsystem.view.HomePage;

/**
 *
 * @author Chinthaka
 */
public class ManageInstructorPanelNew extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public ManageInstructorPanelNew() {
        initComponents();
        cmbGender.setSelectedItem(null);
        buttonDisable();
        checkText();
        getInstructorID();

        loadAllInstructors();

        tblInstructor.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {

                //if (tblInstructor.getSelectedRow() == -1) return;
                if (tblInstructor.getSelectedRow() >= 0) {
                    lblRemove.setEnabled(true);
                }

                if (tblInstructor.getSelectedRow() == -1) {
                    lblRemove.setEnabled(false);
                    return;

                }

                String instructorID = tblInstructor.getValueAt(tblInstructor.getSelectedRow(), 0).toString();
                String instructorName = tblInstructor.getValueAt(tblInstructor.getSelectedRow(), 1).toString();
                String instructorTeleNo = tblInstructor.getValueAt(tblInstructor.getSelectedRow(), 2).toString();
                String instructorNIC = tblInstructor.getValueAt(tblInstructor.getSelectedRow(), 3).toString();
                String instructorAddress = tblInstructor.getValueAt(tblInstructor.getSelectedRow(), 4).toString();
                String instructorGender = tblInstructor.getValueAt(tblInstructor.getSelectedRow(), 5).toString();

                txtInstructorID.setText(instructorID);
                txtInstructorName.setText(instructorName);
                txtInstructorTele.setText(instructorTeleNo);
                txtInstructorNIC.setText(instructorNIC);
                txtInstructorAddress.setText(instructorAddress);
                cmbGender.setSelectedItem(instructorGender);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtInstructorID = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtInstructorName = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtInstructorTele = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtInstructorNIC = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtInstructorAddress = new javax.swing.JTextArea();
        lblSave = new javax.swing.JLabel();
        lblSearch = new javax.swing.JLabel();
        lblRemove = new javax.swing.JLabel();
        lblModify = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        lblNewInstructor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInstructor = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        lblCount = new javax.swing.JLabel();
        cmbGender = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(970, 570));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Stencil Std", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/themify_e73a(0)_48.png"))); // NOI18N
        jLabel2.setText("Manage Instructor..");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 350, 50);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Instructor ID");
        add(jLabel19);
        jLabel19.setBounds(40, 130, 120, 30);

        txtInstructorID.setBackground(new Color(0,0,0,0f));
        txtInstructorID.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtInstructorID.setForeground(new java.awt.Color(255, 255, 255));
        txtInstructorID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtInstructorID.setAutoscrolls(false);
        txtInstructorID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtInstructorID.setCaretColor(new java.awt.Color(255, 255, 255));
        txtInstructorID.setOpaque(false);
        txtInstructorID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInstructorIDActionPerformed(evt);
            }
        });
        txtInstructorID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInstructorIDKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtInstructorIDKeyReleased(evt);
            }
        });
        add(txtInstructorID);
        txtInstructorID.setBounds(230, 130, 150, 30);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText(":");
        add(jLabel15);
        jLabel15.setBounds(170, 130, 20, 30);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Instructor Name");
        add(jLabel20);
        jLabel20.setBounds(40, 180, 120, 30);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText(":");
        add(jLabel16);
        jLabel16.setBounds(170, 180, 20, 30);

        txtInstructorName.setBackground(new Color(0,0,0,0f));
        txtInstructorName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtInstructorName.setForeground(new java.awt.Color(255, 255, 255));
        txtInstructorName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtInstructorName.setAutoscrolls(false);
        txtInstructorName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtInstructorName.setCaretColor(new java.awt.Color(255, 255, 255));
        txtInstructorName.setOpaque(false);
        txtInstructorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInstructorNameActionPerformed(evt);
            }
        });
        txtInstructorName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInstructorNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtInstructorNameKeyReleased(evt);
            }
        });
        add(txtInstructorName);
        txtInstructorName.setBounds(230, 180, 150, 30);

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Gender");
        add(jLabel28);
        jLabel28.setBounds(40, 450, 90, 30);

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText(":");
        add(jLabel27);
        jLabel27.setBounds(170, 450, 20, 30);

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText(":");
        add(jLabel26);
        jLabel26.setBounds(170, 340, 20, 30);

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Instructor Address");
        add(jLabel25);
        jLabel25.setBounds(40, 340, 130, 30);

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Instructor Tele.No");
        add(jLabel21);
        jLabel21.setBounds(40, 230, 130, 30);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText(":");
        add(jLabel17);
        jLabel17.setBounds(170, 230, 20, 30);

        txtInstructorTele.setBackground(new Color(0,0,0,0f));
        txtInstructorTele.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtInstructorTele.setForeground(new java.awt.Color(255, 255, 255));
        txtInstructorTele.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtInstructorTele.setAutoscrolls(false);
        txtInstructorTele.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtInstructorTele.setCaretColor(new java.awt.Color(255, 255, 255));
        txtInstructorTele.setOpaque(false);
        txtInstructorTele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInstructorTeleActionPerformed(evt);
            }
        });
        txtInstructorTele.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInstructorTeleKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtInstructorTeleKeyReleased(evt);
            }
        });
        add(txtInstructorTele);
        txtInstructorTele.setBounds(230, 230, 150, 30);

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Instructor NIC");
        add(jLabel22);
        jLabel22.setBounds(40, 280, 120, 30);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText(":");
        add(jLabel18);
        jLabel18.setBounds(170, 280, 20, 30);

        txtInstructorNIC.setBackground(new Color(0,0,0,0f));
        txtInstructorNIC.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtInstructorNIC.setForeground(new java.awt.Color(255, 255, 255));
        txtInstructorNIC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtInstructorNIC.setAutoscrolls(false);
        txtInstructorNIC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtInstructorNIC.setCaretColor(new java.awt.Color(255, 255, 255));
        txtInstructorNIC.setOpaque(false);
        txtInstructorNIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInstructorNICActionPerformed(evt);
            }
        });
        txtInstructorNIC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInstructorNICKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtInstructorNICKeyReleased(evt);
            }
        });
        add(txtInstructorNIC);
        txtInstructorNIC.setBounds(230, 280, 150, 30);

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setOpaque(false);

        txtInstructorAddress.setBackground(new Color(0,0,0,0f));
        txtInstructorAddress.setColumns(20);
        txtInstructorAddress.setRows(5);
        txtInstructorAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtInstructorAddress.setOpaque(false);
        txtInstructorAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtInstructorAddressKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(txtInstructorAddress);

        add(jScrollPane2);
        jScrollPane2.setBounds(230, 330, 230, 110);

        lblSave.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblSave.setForeground(new java.awt.Color(255, 255, 255));
        lblSave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/save.png"))); // NOI18N
        lblSave.setText("Save");
        lblSave.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblSave.setEnabled(false);
        lblSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSaveMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSaveMouseClicked(evt);
            }
        });
        add(lblSave);
        lblSave.setBounds(400, 510, 90, 40);

        lblSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/search.png"))); // NOI18N
        lblSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSearchMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSearchMouseClicked(evt);
            }
        });
        add(lblSearch);
        lblSearch.setBounds(390, 120, 50, 50);

        lblRemove.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblRemove.setForeground(new java.awt.Color(255, 255, 255));
        lblRemove.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRemove.setText("Remove Instructor");
        lblRemove.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRemoveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRemoveMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRemoveMouseClicked(evt);
            }
        });
        add(lblRemove);
        lblRemove.setBounds(680, 490, 220, 30);

        lblModify.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblModify.setForeground(new java.awt.Color(255, 255, 255));
        lblModify.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModify.setText("Modify Instructor");
        lblModify.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblModify.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblModifyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblModifyMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblModifyMouseClicked(evt);
            }
        });
        add(lblModify);
        lblModify.setBounds(680, 430, 220, 30);

        jLabel32.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(255, 153, 51), new java.awt.Color(255, 153, 51), new java.awt.Color(255, 153, 51), new java.awt.Color(255, 153, 51)));
        add(jLabel32);
        jLabel32.setBounds(660, 410, 260, 130);

        lblNewInstructor.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblNewInstructor.setForeground(new java.awt.Color(255, 255, 255));
        lblNewInstructor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNewInstructor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/add.png"))); // NOI18N
        lblNewInstructor.setText("New Instructor");
        lblNewInstructor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblNewInstructor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNewInstructorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNewInstructorMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblNewInstructorMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNewInstructorMouseClicked(evt);
            }
        });
        add(lblNewInstructor);
        lblNewInstructor.setBounds(40, 90, 220, 30);

        tblInstructor.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        tblInstructor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "TeleNo", "NIC", "Address", "Gender"
            }
        ));
        tblInstructor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tblInstructor);

        add(jScrollPane1);
        jScrollPane1.setBounds(470, 130, 470, 180);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Count of All Instructors :-");
        add(jLabel5);
        jLabel5.setBounds(470, 320, 200, 20);

        lblCount.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblCount.setForeground(new java.awt.Color(255, 255, 255));
        lblCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCount.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        lblCount.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblCountAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        add(lblCount);
        lblCount.setBounds(670, 320, 50, 20);

        cmbGender.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        cmbGender.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        cmbGender.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cmbGenderKeyReleased(evt);
            }
        });
        add(cmbGender);
        cmbGender.setBounds(230, 450, 150, 30);

        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(255, 153, 51), new java.awt.Color(255, 153, 51), new java.awt.Color(255, 153, 51), new java.awt.Color(255, 153, 51)));
        add(jLabel3);
        jLabel3.setBounds(20, 70, 930, 490);

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/back.png"))); // NOI18N
        jLabel23.setText("BACK");
        jLabel23.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        add(jLabel23);
        jLabel23.setBounds(840, 10, 120, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/Untitled-1.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 3));
        add(jLabel1);
        jLabel1.setBounds(0, 0, 970, 570);
    }// </editor-fold>//GEN-END:initComponents

    private void txtInstructorIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInstructorIDActionPerformed
        txtInstructorName.requestFocus();
    }//GEN-LAST:event_txtInstructorIDActionPerformed

    private void txtInstructorIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInstructorIDKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInstructorIDKeyPressed

    private void txtInstructorIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInstructorIDKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInstructorIDKeyReleased

    private void txtInstructorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInstructorNameActionPerformed
        txtInstructorTele.requestFocus();
    }//GEN-LAST:event_txtInstructorNameActionPerformed

    private void txtInstructorNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInstructorNameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInstructorNameKeyPressed

    private void txtInstructorNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInstructorNameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInstructorNameKeyReleased

    private void txtInstructorTeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInstructorTeleActionPerformed
        txtInstructorNIC.requestFocus();
    }//GEN-LAST:event_txtInstructorTeleActionPerformed

    private void txtInstructorTeleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInstructorTeleKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInstructorTeleKeyPressed

    private void txtInstructorTeleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInstructorTeleKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInstructorTeleKeyReleased

    private void txtInstructorNICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInstructorNICActionPerformed
        txtInstructorAddress.requestFocus();
    }//GEN-LAST:event_txtInstructorNICActionPerformed

    private void txtInstructorNICKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInstructorNICKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInstructorNICKeyPressed

    private void txtInstructorNICKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInstructorNICKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInstructorNICKeyReleased

    private void lblNewInstructorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewInstructorMouseClicked
        clearAllTextFileds();
        getInstructorID();
        txtInstructorName.requestFocusInWindow();
    }//GEN-LAST:event_lblNewInstructorMouseClicked

    private void lblNewInstructorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewInstructorMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNewInstructorMousePressed

    private void lblSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaveMouseClicked
        try {
            InstructorDTO instructor = new InstructorDTO(txtInstructorID.getText(),
                    txtInstructorName.getText(),
                    txtInstructorTele.getText(),
                    txtInstructorNIC.getText(),
                    txtInstructorAddress.getText(),
                    cmbGender.getSelectedItem().toString());

            boolean result = ManageInstructorController.addInstructor(instructor);

            if (result) {
                JOptionPane.showMessageDialog(this, "Instructor has been successfully Saved.");
                loadAllInstructors();
                getInstructorID();
                
                lblSave.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(this, "Instructor hasn't been Saved due to some error");
                lblSave.setEnabled(true);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Fill All Fields");
        }
        clearAllTextFileds();
        txtInstructorName.requestFocus();
    }//GEN-LAST:event_lblSaveMouseClicked

    private void lblRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRemoveMouseClicked
        InstructorDTO instructor = new InstructorDTO(txtInstructorID.getText(),
                txtInstructorName.getText(),
                txtInstructorTele.getText(),
                txtInstructorNIC.getText(),
                txtInstructorAddress.getText(),
                cmbGender.getSelectedItem().toString());
        try {
            boolean result = ManageInstructorController.deleteInstructor(instructor);

            if (result) {
                JOptionPane.showMessageDialog(this, "Instructor has been successfully deleted.");
                loadAllInstructors();
                lblSave.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(this, "Instructor hasn't been deleted due to some error");
            }

        } catch (Exception ex) {
            Logger.getLogger(ManageInstructorPanelNew.class.getName()).log(Level.SEVERE, null, ex);
        }
        clearAllTextFileds();
        txtInstructorID.setText("");
    }//GEN-LAST:event_lblRemoveMouseClicked

    private void lblCountAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblCountAncestorAdded

    }//GEN-LAST:event_lblCountAncestorAdded

    private void lblModifyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModifyMouseClicked
        InstructorDTO instructor = new InstructorDTO(txtInstructorID.getText(),
                txtInstructorName.getText(),
                txtInstructorTele.getText(),
                txtInstructorNIC.getText(),
                txtInstructorAddress.getText(),
                cmbGender.getSelectedItem().toString());
        try {
            boolean result = ManageInstructorController.updateInstructor(instructor);

            if (result) {
                JOptionPane.showMessageDialog(this, "Instructor has been successfully Updated.");
                loadAllInstructors();
                clearAllTextFileds();
                txtInstructorID.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Instructor hasn't been Updated due to some error");
            }

        } catch (Exception ex) {
            Logger.getLogger(ManageInstructorPanelNew.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_lblModifyMouseClicked

    private void lblSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchMouseClicked
        
        try {
            InstructorDTO instructorDTO = ManageInstructorController.searchInstructor(txtInstructorID.getText());
            txtInstructorName.setText(instructorDTO.getInstructorName());
            txtInstructorTele.setText(instructorDTO.getInstructorTeleNo());
            txtInstructorNIC.setText(instructorDTO.getInstructorNIC());
            txtInstructorAddress.setText(instructorDTO.getInstructorAddress());
            cmbGender.setSelectedItem(instructorDTO.getGender());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "No Instructor");
        }
    }//GEN-LAST:event_lblSearchMouseClicked

    private void lblNewInstructorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewInstructorMouseEntered
        lblNewInstructor.setSize(230, 40);
    }//GEN-LAST:event_lblNewInstructorMouseEntered

    private void lblNewInstructorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewInstructorMouseExited
        lblNewInstructor.setSize(220, 30);
    }//GEN-LAST:event_lblNewInstructorMouseExited

    private void lblModifyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModifyMouseEntered
        lblModify.setSize(230, 40);
    }//GEN-LAST:event_lblModifyMouseEntered

    private void lblModifyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModifyMouseExited
        lblModify.setSize(220, 30);
    }//GEN-LAST:event_lblModifyMouseExited

    private void lblRemoveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRemoveMouseEntered
        lblRemove.setSize(230, 40);
    }//GEN-LAST:event_lblRemoveMouseEntered

    private void lblRemoveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRemoveMouseExited
        lblRemove.setSize(220, 30);
    }//GEN-LAST:event_lblRemoveMouseExited

    private void lblSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaveMouseEntered
        lblSave.setSize(100, 50);
    }//GEN-LAST:event_lblSaveMouseEntered

    private void lblSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaveMouseExited
        lblSave.setSize(90, 40);
    }//GEN-LAST:event_lblSaveMouseExited

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        HomePanel hp = new HomePanel();
        JPanel middlePanel = HomePage.getMainPanel();
        middlePanel.removeAll();
        hp.setSize(middlePanel.getSize());
        middlePanel.add(hp);
        middlePanel.revalidate();
        middlePanel.repaint();
    }//GEN-LAST:event_jLabel23MouseClicked

    private void cmbGenderKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbGenderKeyReleased

    }//GEN-LAST:event_cmbGenderKeyReleased

    private void lblSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchMouseEntered
        lblSearch.setSize(60, 60);
    }//GEN-LAST:event_lblSearchMouseEntered

    private void lblSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchMouseExited
        lblSearch.setSize(50, 50);
    }//GEN-LAST:event_lblSearchMouseExited

    private void txtInstructorAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInstructorAddressKeyReleased
        checkText();        // TODO add your handling code here:
    }//GEN-LAST:event_txtInstructorAddressKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCount;
    private javax.swing.JLabel lblModify;
    private javax.swing.JLabel lblNewInstructor;
    private javax.swing.JLabel lblRemove;
    private javax.swing.JLabel lblSave;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JTable tblInstructor;
    private javax.swing.JTextArea txtInstructorAddress;
    private javax.swing.JTextField txtInstructorID;
    private javax.swing.JTextField txtInstructorNIC;
    private javax.swing.JTextField txtInstructorName;
    private javax.swing.JTextField txtInstructorTele;
    // End of variables declaration//GEN-END:variables

    private void clearAllTextFileds() {
        txtInstructorName.setText("");
        txtInstructorTele.setText("");
        txtInstructorNIC.setText("");
        txtInstructorAddress.setText("");
        cmbGender.setSelectedItem(null);

    }

    private void loadAllInstructors() {
        try {
            ArrayList<InstructorDTO> allInstructors = ManageInstructorController.getAllInstructor();

            DefaultTableModel dtm = (DefaultTableModel) tblInstructor.getModel();

            dtm.setRowCount(0);

            if (allInstructors != null) {

                for (InstructorDTO inventory : allInstructors) {

                    Object[] rowData = {
                        inventory.getInstructorID(),
                        inventory.getInstructorName(),
                        inventory.getInstructorTeleNo(),
                        inventory.getInstructorNIC(),
                        inventory.getInstructorAddress(),
                        inventory.getGender()
                    };

                    dtm.addRow(rowData);

                }

            }
            lblCount.setText(Integer.toString(tblInstructor.getRowCount()));

        } catch (Exception ex) {
            Logger.getLogger(ManageInstructorPanelNew.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void buttonDisable() {
        lblRemove.setEnabled(false);
    }
    private void checkText() {
        String id = txtInstructorID.getText();
        String name = txtInstructorName.getText();
        String tele = txtInstructorTele.getText();
        String nic = txtInstructorNIC.getText();
        String address = txtInstructorAddress.getText();

        if ((id.equals("")) && (name.equals("")) && (tele.equals("")) && (nic.equals("")) && (address.equals(""))) {
            lblSave.setEnabled(false);
        } else {
            lblSave.setEnabled(true);
        }
    }
    
    private void getInstructorID() {
        String newID;
        try {
            newID = IDGenarator.getNewID("instructor","Instructor_ID", "Ins");
            txtInstructorID.setText(newID);

        } catch (SQLException ex) {
            Logger.getLogger(RegMemberPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegMemberPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
