/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.mygymmanagement.view.panel;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import lk.ijse.mygymmanagement.controller.ManageInstructorController;
import lk.ijse.mygymmanagement.controller.MemberHealthController;
import lk.ijse.mygymmanagementsystem.commmon.IDGenarator;
import lk.ijse.mygymmanagementsystem.core.dto.InstructorDTO;
import lk.ijse.mygymmanagementsystem.core.dto.MemberHealthDTO;
import lk.ijse.mygymmanagementsystem.view.HomePage;

/**
 *
 * @author Chinthaka
 */
public class ManageMemberHealthHistory extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public ManageMemberHealthHistory() {
        initComponents();
        getMemberHealthID();
        txtMemberID.setText(RegMemberPanel.getMemberID());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cmbBlood = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        checkD_N = new javax.swing.JCheckBox();
        checkD_Y = new javax.swing.JCheckBox();
        checkH_Y = new javax.swing.JCheckBox();
        checkSoDU_Y = new javax.swing.JCheckBox();
        checkPoTitC_Y = new javax.swing.JCheckBox();
        checkHC_Y = new javax.swing.JCheckBox();
        checkEoF_Y = new javax.swing.JCheckBox();
        checkA_Y = new javax.swing.JCheckBox();
        checkLoKC_Y = new javax.swing.JCheckBox();
        checkHBP_Y = new javax.swing.JCheckBox();
        checkH_N = new javax.swing.JCheckBox();
        checkLoKC_N = new javax.swing.JCheckBox();
        checkA_N = new javax.swing.JCheckBox();
        checkSoDU_N = new javax.swing.JCheckBox();
        checkHC_N = new javax.swing.JCheckBox();
        checkEoF_N = new javax.swing.JCheckBox();
        checkHBP_N = new javax.swing.JCheckBox();
        checkPoTitC_N = new javax.swing.JCheckBox();
        jLabel25 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        checkHAS_Y = new javax.swing.JCheckBox();
        checkHAS_N = new javax.swing.JCheckBox();
        jLabel19 = new javax.swing.JLabel();
        checkFA_Y = new javax.swing.JCheckBox();
        checkAfptE_Y = new javax.swing.JCheckBox();
        checkDiboCc_Y = new javax.swing.JCheckBox();
        checkFA_N = new javax.swing.JCheckBox();
        checkAfptE_N = new javax.swing.JCheckBox();
        checkDiboCc_N = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtMemberID = new javax.swing.JTextField();
        btnRegistor = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtMHealthID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(970, 570));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Stencil Std", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/manageUser.png"))); // NOI18N
        jLabel2.setText("Manage Member health..");
        add(jLabel2);
        jLabel2.setBounds(20, 10, 410, 50);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Blood Group");
        add(jLabel17);
        jLabel17.setBounds(700, 110, 110, 30);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText(":");
        add(jLabel16);
        jLabel16.setBounds(810, 110, 20, 30);

        cmbBlood.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cmbBlood.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        cmbBlood.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        add(cmbBlood);
        cmbBlood.setBounds(840, 110, 80, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Please indicate if your suffer form or have suffer any of the following ");
        add(jLabel3);
        jLabel3.setBounds(20, 110, 460, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("conditions,");
        add(jLabel4);
        jLabel4.setBounds(20, 130, 80, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("High Blood Pressure");
        add(jLabel6);
        jLabel6.setBounds(30, 210, 140, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Epilepsy or Fits");
        add(jLabel11);
        jLabel11.setBounds(30, 250, 140, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("High Cholesterol");
        add(jLabel10);
        jLabel10.setBounds(30, 290, 140, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Stomach or Duodenal Ulcer");
        add(jLabel9);
        jLabel9.setBounds(30, 330, 180, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Liver or Kidney Condition");
        add(jLabel8);
        jLabel8.setBounds(30, 370, 170, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Hernia");
        add(jLabel7);
        jLabel7.setBounds(30, 490, 190, 30);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Advice from physician to Exercise");
        add(jLabel12);
        jLabel12.setBounds(480, 290, 270, 30);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Heart Attack/Stroke");
        add(jLabel13);
        jLabel13.setBounds(30, 170, 140, 30);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Pain or Tightness in the Chest");
        add(jLabel20);
        jLabel20.setBounds(30, 410, 190, 30);

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Diabetes");
        add(jLabel22);
        jLabel22.setBounds(30, 450, 190, 30);

        checkD_N.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        checkD_N.setForeground(new java.awt.Color(255, 255, 255));
        checkD_N.setText("No");
        checkD_N.setOpaque(false);
        checkD_N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkD_NActionPerformed(evt);
            }
        });
        add(checkD_N);
        checkD_N.setBounds(320, 450, 60, 25);

        checkD_Y.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        checkD_Y.setForeground(new java.awt.Color(255, 255, 255));
        checkD_Y.setText("Yes");
        checkD_Y.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        checkD_Y.setOpaque(false);
        add(checkD_Y);
        checkD_Y.setBounds(260, 450, 60, 25);

        checkH_Y.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        checkH_Y.setForeground(new java.awt.Color(255, 255, 255));
        checkH_Y.setText("Yes");
        checkH_Y.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        checkH_Y.setOpaque(false);
        add(checkH_Y);
        checkH_Y.setBounds(260, 490, 60, 25);

        checkSoDU_Y.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        checkSoDU_Y.setForeground(new java.awt.Color(255, 255, 255));
        checkSoDU_Y.setText("Yes");
        checkSoDU_Y.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        checkSoDU_Y.setOpaque(false);
        add(checkSoDU_Y);
        checkSoDU_Y.setBounds(260, 330, 60, 25);

        checkPoTitC_Y.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        checkPoTitC_Y.setForeground(new java.awt.Color(255, 255, 255));
        checkPoTitC_Y.setText("Yes");
        checkPoTitC_Y.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        checkPoTitC_Y.setOpaque(false);
        add(checkPoTitC_Y);
        checkPoTitC_Y.setBounds(260, 410, 60, 25);

        checkHC_Y.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        checkHC_Y.setForeground(new java.awt.Color(255, 255, 255));
        checkHC_Y.setText("Yes");
        checkHC_Y.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        checkHC_Y.setOpaque(false);
        add(checkHC_Y);
        checkHC_Y.setBounds(260, 290, 60, 25);

        checkEoF_Y.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        checkEoF_Y.setForeground(new java.awt.Color(255, 255, 255));
        checkEoF_Y.setText("Yes");
        checkEoF_Y.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        checkEoF_Y.setOpaque(false);
        add(checkEoF_Y);
        checkEoF_Y.setBounds(260, 250, 60, 25);

        checkA_Y.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        checkA_Y.setForeground(new java.awt.Color(255, 255, 255));
        checkA_Y.setText("Yes");
        checkA_Y.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        checkA_Y.setOpaque(false);
        add(checkA_Y);
        checkA_Y.setBounds(770, 210, 60, 25);

        checkLoKC_Y.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        checkLoKC_Y.setForeground(new java.awt.Color(255, 255, 255));
        checkLoKC_Y.setText("Yes");
        checkLoKC_Y.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        checkLoKC_Y.setOpaque(false);
        add(checkLoKC_Y);
        checkLoKC_Y.setBounds(260, 370, 60, 25);

        checkHBP_Y.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        checkHBP_Y.setForeground(new java.awt.Color(255, 255, 255));
        checkHBP_Y.setText("Yes");
        checkHBP_Y.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        checkHBP_Y.setOpaque(false);
        add(checkHBP_Y);
        checkHBP_Y.setBounds(260, 210, 60, 25);

        checkH_N.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        checkH_N.setForeground(new java.awt.Color(255, 255, 255));
        checkH_N.setText("No");
        checkH_N.setOpaque(false);
        checkH_N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkH_NActionPerformed(evt);
            }
        });
        add(checkH_N);
        checkH_N.setBounds(320, 490, 60, 25);

        checkLoKC_N.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        checkLoKC_N.setForeground(new java.awt.Color(255, 255, 255));
        checkLoKC_N.setText("No");
        checkLoKC_N.setOpaque(false);
        checkLoKC_N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkLoKC_NActionPerformed(evt);
            }
        });
        add(checkLoKC_N);
        checkLoKC_N.setBounds(320, 370, 60, 25);

        checkA_N.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        checkA_N.setForeground(new java.awt.Color(255, 255, 255));
        checkA_N.setText("No");
        checkA_N.setOpaque(false);
        checkA_N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkA_NActionPerformed(evt);
            }
        });
        add(checkA_N);
        checkA_N.setBounds(840, 210, 60, 25);

        checkSoDU_N.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        checkSoDU_N.setForeground(new java.awt.Color(255, 255, 255));
        checkSoDU_N.setText("No");
        checkSoDU_N.setOpaque(false);
        checkSoDU_N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSoDU_NActionPerformed(evt);
            }
        });
        add(checkSoDU_N);
        checkSoDU_N.setBounds(320, 330, 60, 25);

        checkHC_N.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        checkHC_N.setForeground(new java.awt.Color(255, 255, 255));
        checkHC_N.setText("No");
        checkHC_N.setOpaque(false);
        checkHC_N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkHC_NActionPerformed(evt);
            }
        });
        add(checkHC_N);
        checkHC_N.setBounds(320, 290, 60, 25);

        checkEoF_N.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        checkEoF_N.setForeground(new java.awt.Color(255, 255, 255));
        checkEoF_N.setText("No");
        checkEoF_N.setOpaque(false);
        checkEoF_N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkEoF_NActionPerformed(evt);
            }
        });
        add(checkEoF_N);
        checkEoF_N.setBounds(320, 250, 60, 25);

        checkHBP_N.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        checkHBP_N.setForeground(new java.awt.Color(255, 255, 255));
        checkHBP_N.setText("No");
        checkHBP_N.setOpaque(false);
        checkHBP_N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkHBP_NActionPerformed(evt);
            }
        });
        add(checkHBP_N);
        checkHBP_N.setBounds(320, 210, 60, 25);

        checkPoTitC_N.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        checkPoTitC_N.setForeground(new java.awt.Color(255, 255, 255));
        checkPoTitC_N.setText("No");
        checkPoTitC_N.setOpaque(false);
        checkPoTitC_N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPoTitC_NActionPerformed(evt);
            }
        });
        add(checkPoTitC_N);
        checkPoTitC_N.setBounds(320, 410, 60, 25);

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Asthma");
        add(jLabel25);
        jLabel25.setBounds(480, 210, 270, 30);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Difficulty in breathing or Chronic coughs");
        add(jLabel15);
        jLabel15.setBounds(480, 170, 270, 30);

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Fainting Attacks");
        add(jLabel26);
        jLabel26.setBounds(480, 250, 270, 30);

        checkHAS_Y.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        checkHAS_Y.setForeground(new java.awt.Color(255, 255, 255));
        checkHAS_Y.setText("Yes");
        checkHAS_Y.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        checkHAS_Y.setOpaque(false);
        add(checkHAS_Y);
        checkHAS_Y.setBounds(260, 170, 60, 25);

        checkHAS_N.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        checkHAS_N.setForeground(new java.awt.Color(255, 255, 255));
        checkHAS_N.setText("No");
        checkHAS_N.setOpaque(false);
        checkHAS_N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkHAS_NActionPerformed(evt);
            }
        });
        add(checkHAS_N);
        checkHAS_N.setBounds(320, 170, 60, 25);

        jLabel19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(255, 153, 51), new java.awt.Color(255, 153, 51), new java.awt.Color(255, 153, 51), new java.awt.Color(255, 153, 51)));
        add(jLabel19);
        jLabel19.setBounds(20, 160, 380, 380);

        checkFA_Y.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        checkFA_Y.setForeground(new java.awt.Color(255, 255, 255));
        checkFA_Y.setText("Yes");
        checkFA_Y.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        checkFA_Y.setOpaque(false);
        add(checkFA_Y);
        checkFA_Y.setBounds(770, 250, 60, 25);

        checkAfptE_Y.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        checkAfptE_Y.setForeground(new java.awt.Color(255, 255, 255));
        checkAfptE_Y.setText("Yes");
        checkAfptE_Y.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        checkAfptE_Y.setOpaque(false);
        add(checkAfptE_Y);
        checkAfptE_Y.setBounds(770, 290, 60, 25);

        checkDiboCc_Y.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        checkDiboCc_Y.setForeground(new java.awt.Color(255, 255, 255));
        checkDiboCc_Y.setText("Yes");
        checkDiboCc_Y.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        checkDiboCc_Y.setOpaque(false);
        add(checkDiboCc_Y);
        checkDiboCc_Y.setBounds(770, 170, 60, 25);

        checkFA_N.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        checkFA_N.setForeground(new java.awt.Color(255, 255, 255));
        checkFA_N.setText("No");
        checkFA_N.setOpaque(false);
        checkFA_N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkFA_NActionPerformed(evt);
            }
        });
        add(checkFA_N);
        checkFA_N.setBounds(840, 250, 60, 25);

        checkAfptE_N.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        checkAfptE_N.setForeground(new java.awt.Color(255, 255, 255));
        checkAfptE_N.setText("No");
        checkAfptE_N.setOpaque(false);
        checkAfptE_N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAfptE_NActionPerformed(evt);
            }
        });
        add(checkAfptE_N);
        checkAfptE_N.setBounds(840, 290, 60, 25);

        checkDiboCc_N.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        checkDiboCc_N.setForeground(new java.awt.Color(255, 255, 255));
        checkDiboCc_N.setText("No");
        checkDiboCc_N.setOpaque(false);
        checkDiboCc_N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkDiboCc_NActionPerformed(evt);
            }
        });
        add(checkDiboCc_N);
        checkDiboCc_N.setBounds(840, 170, 60, 25);

        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(255, 153, 51), new java.awt.Color(255, 153, 51), new java.awt.Color(255, 153, 51), new java.awt.Color(255, 153, 51)));
        add(jLabel5);
        jLabel5.setBounds(460, 160, 460, 180);

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/back.png"))); // NOI18N
        jLabel21.setText("BACK");
        jLabel21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        add(jLabel21);
        jLabel21.setBounds(840, 10, 120, 50);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Member ID");
        add(jLabel14);
        jLabel14.setBounds(700, 70, 100, 30);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText(":");
        add(jLabel18);
        jLabel18.setBounds(810, 70, 20, 30);

        txtMemberID.setBackground(new Color(0,0,0,0f));
        txtMemberID.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtMemberID.setForeground(new java.awt.Color(255, 255, 255));
        txtMemberID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMemberID.setAutoscrolls(false);
        txtMemberID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtMemberID.setCaretColor(new java.awt.Color(255, 255, 255));
        txtMemberID.setOpaque(false);
        txtMemberID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMemberIDActionPerformed(evt);
            }
        });
        txtMemberID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMemberIDKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMemberIDKeyReleased(evt);
            }
        });
        add(txtMemberID);
        txtMemberID.setBounds(840, 70, 120, 30);

        btnRegistor.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnRegistor.setText("Register");
        btnRegistor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegistor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistorMouseExited(evt);
            }
        });
        btnRegistor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistorActionPerformed(evt);
            }
        });
        add(btnRegistor);
        btnRegistor.setBounds(820, 430, 100, 30);

        btnCancel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelMouseExited(evt);
            }
        });
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        add(btnCancel);
        btnCancel.setBounds(680, 430, 100, 30);

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Member Healt ID");
        add(jLabel23);
        jLabel23.setBounds(20, 80, 150, 30);

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText(":");
        add(jLabel24);
        jLabel24.setBounds(170, 80, 20, 30);

        txtMHealthID.setBackground(new Color(0,0,0,0f));
        txtMHealthID.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtMHealthID.setForeground(new java.awt.Color(255, 255, 255));
        txtMHealthID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMHealthID.setAutoscrolls(false);
        txtMHealthID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtMHealthID.setCaretColor(new java.awt.Color(255, 255, 255));
        txtMHealthID.setOpaque(false);
        txtMHealthID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMHealthIDActionPerformed(evt);
            }
        });
        txtMHealthID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMHealthIDKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMHealthIDKeyReleased(evt);
            }
        });
        add(txtMHealthID);
        txtMHealthID.setBounds(210, 80, 160, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/Untitled-1.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 3));
        add(jLabel1);
        jLabel1.setBounds(0, 0, 970, 570);
    }// </editor-fold>//GEN-END:initComponents

    private void checkD_NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkD_NActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkD_NActionPerformed

    private void checkH_NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkH_NActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkH_NActionPerformed

    private void checkLoKC_NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkLoKC_NActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkLoKC_NActionPerformed

    private void checkA_NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkA_NActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkA_NActionPerformed

    private void checkSoDU_NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSoDU_NActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkSoDU_NActionPerformed

    private void checkHC_NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkHC_NActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkHC_NActionPerformed

    private void checkEoF_NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkEoF_NActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkEoF_NActionPerformed

    private void checkHBP_NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkHBP_NActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkHBP_NActionPerformed

    private void checkPoTitC_NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPoTitC_NActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkPoTitC_NActionPerformed

    private void checkHAS_NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkHAS_NActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkHAS_NActionPerformed

    private void checkFA_NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkFA_NActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkFA_NActionPerformed

    private void checkAfptE_NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAfptE_NActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkAfptE_NActionPerformed

    private void checkDiboCc_NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkDiboCc_NActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkDiboCc_NActionPerformed

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        RegMemberPanel memberPanel = new RegMemberPanel();
        JPanel middlePanel = HomePage.getMainPanel();
        middlePanel.removeAll();
        memberPanel.setSize(middlePanel.getSize());
        middlePanel.add(memberPanel);
        middlePanel.revalidate();
        middlePanel.repaint();
    }//GEN-LAST:event_jLabel21MouseClicked

    private void txtMemberIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMemberIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMemberIDActionPerformed

    private void txtMemberIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMemberIDKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMemberIDKeyPressed

    private void txtMemberIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMemberIDKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMemberIDKeyReleased

    private void btnRegistorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistorActionPerformed

      try {
            MemberHealthDTO health = new MemberHealthDTO(
                    txtMHealthID.getText(),
                    txtMemberID.getText(),
                    cmbBlood.getSelectedItem().toString(),
                    checkHAS_Y.isSelected()?true:checkHAS_N.isSelected()?false:false,
                    checkHBP_Y.isSelected()?true:checkHBP_N.isSelected()?false:false,
                    checkEoF_Y.isSelected()?true:checkEoF_N.isSelected()?false:false,
                    checkHC_Y.isSelected()?true:checkHC_N.isSelected()?false:false,
                    checkSoDU_Y.isSelected()?true:checkSoDU_N.isSelected()?false:false,
                    checkLoKC_Y.isSelected()?true:checkLoKC_N.isSelected()?false:false,
                    checkPoTitC_Y.isSelected()?true:checkPoTitC_N.isSelected()?false:false,
                    checkD_Y.isSelected()?true:checkD_N.isSelected()?false:false,
                    checkH_Y.isSelected()?true:checkH_N.isSelected()?false:false,
                    checkDiboCc_Y.isSelected()?true:checkDiboCc_N.isSelected()?false:false,
                    checkA_Y.isSelected()?true:checkA_N.isSelected()?false:false,
                    checkFA_Y.isSelected()?true:checkFA_N.isSelected()?false:false,
                    checkAfptE_Y.isSelected()?true:checkAfptE_N.isSelected()?false:false);

            boolean result = MemberHealthController.addHealth(health);

            if (result) {
                JOptionPane.showMessageDialog(this, "Registration successfully.");
            } else {
                JOptionPane.showMessageDialog(this, "Registration Faild");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
      
        PaymentPanel paymentPanel = new PaymentPanel();
        JPanel middlePanel = HomePage.getMainPanel();
        middlePanel.removeAll();
        paymentPanel.setSize(middlePanel.getSize());
        middlePanel.add(paymentPanel);
        middlePanel.revalidate();
        middlePanel.repaint();
        
        
    }//GEN-LAST:event_btnRegistorActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtMHealthIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMHealthIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMHealthIDActionPerformed

    private void txtMHealthIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMHealthIDKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMHealthIDKeyPressed

    private void txtMHealthIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMHealthIDKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMHealthIDKeyReleased

    private void btnCancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseEntered
        btnCancel.setSize(110, 40);
    }//GEN-LAST:event_btnCancelMouseEntered

    private void btnCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseExited
       btnCancel.setSize(100, 30);
    }//GEN-LAST:event_btnCancelMouseExited

    private void btnRegistorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistorMouseEntered
        btnRegistor.setSize(110, 40);
    }//GEN-LAST:event_btnRegistorMouseEntered

    private void btnRegistorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistorMouseExited
        btnRegistor.setSize(100, 30);
    }//GEN-LAST:event_btnRegistorMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnRegistor;
    private javax.swing.JCheckBox checkA_N;
    private javax.swing.JCheckBox checkA_Y;
    private javax.swing.JCheckBox checkAfptE_N;
    private javax.swing.JCheckBox checkAfptE_Y;
    private javax.swing.JCheckBox checkD_N;
    private javax.swing.JCheckBox checkD_Y;
    private javax.swing.JCheckBox checkDiboCc_N;
    private javax.swing.JCheckBox checkDiboCc_Y;
    private javax.swing.JCheckBox checkEoF_N;
    private javax.swing.JCheckBox checkEoF_Y;
    private javax.swing.JCheckBox checkFA_N;
    private javax.swing.JCheckBox checkFA_Y;
    private javax.swing.JCheckBox checkHAS_N;
    private javax.swing.JCheckBox checkHAS_Y;
    private javax.swing.JCheckBox checkHBP_N;
    private javax.swing.JCheckBox checkHBP_Y;
    private javax.swing.JCheckBox checkHC_N;
    private javax.swing.JCheckBox checkHC_Y;
    private javax.swing.JCheckBox checkH_N;
    private javax.swing.JCheckBox checkH_Y;
    private javax.swing.JCheckBox checkLoKC_N;
    private javax.swing.JCheckBox checkLoKC_Y;
    private javax.swing.JCheckBox checkPoTitC_N;
    private javax.swing.JCheckBox checkPoTitC_Y;
    private javax.swing.JCheckBox checkSoDU_N;
    private javax.swing.JCheckBox checkSoDU_Y;
    private javax.swing.JComboBox<String> cmbBlood;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtMHealthID;
    private javax.swing.JTextField txtMemberID;
    // End of variables declaration//GEN-END:variables
    
    private void getMemberHealthID() {
        String newID;
        try {
            newID = IDGenarator.getNewID("memberhealth","Member_Health_ID", "MHI");
            txtMHealthID.setText(newID);

        } catch (SQLException ex) {
            Logger.getLogger(RegMemberPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegMemberPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
