/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.mygymmanagement.view.panel;

import java.awt.Color;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import lk.ijse.mygymmanagement.controller.ManageInventoryController;
import lk.ijse.mygymmanagementsystem.commmon.IDGenarator;
import lk.ijse.mygymmanagementsystem.core.dto.InventoryDTO;

/**
 *
 * @author Chinthaka
 */
public class ManageInventoryPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public ManageInventoryPanel() {
        initComponents();
        buttonDisable();
        loadAllInventory();
        getInventoryID();
        checkText();
        
        
        tblInventory.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                
                if (tblInventory.getSelectedRow() >= 0) {
                    lblRemove.setEnabled(true);
                }
                
                if (tblInventory.getSelectedRow() == -1) {
                    lblRemove.setEnabled(false);
                    return;
                    
                }
                
                String inventoryID = tblInventory.getValueAt(tblInventory.getSelectedRow(), 0).toString();
                String inventoryName = tblInventory.getValueAt(tblInventory.getSelectedRow(), 1).toString();
                String brandName = tblInventory.getValueAt(tblInventory.getSelectedRow(), 2).toString();
                String qty = tblInventory.getValueAt(tblInventory.getSelectedRow(), 3).toString();
                
                txtInventoryID.setText(inventoryID);
                txtInventoryName.setText(inventoryName);
                txtBrandName.setText(brandName);
                txtQty.setText(qty);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtInventoryID = new javax.swing.JTextField();
        txtInventoryName = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtBrandName = new javax.swing.JTextField();
        txtQty = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lblSearch = new javax.swing.JLabel();
        lblNewInventory = new javax.swing.JLabel();
        lblModify = new javax.swing.JLabel();
        lblRemove = new javax.swing.JLabel();
        lblSave = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInventory = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        lblCount = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(970, 570));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Stencil Std", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/Typicons_e0f9(0)_48.png"))); // NOI18N
        jLabel2.setText("Manage Inventory..");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 340, 50);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Inventory ID");
        add(jLabel19);
        jLabel19.setBounds(70, 130, 140, 30);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText(":");
        add(jLabel15);
        jLabel15.setBounds(230, 130, 20, 30);

        txtInventoryID.setBackground(new Color(0,0,0,0f));
        txtInventoryID.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtInventoryID.setForeground(new java.awt.Color(255, 255, 255));
        txtInventoryID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtInventoryID.setAutoscrolls(false);
        txtInventoryID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtInventoryID.setCaretColor(new java.awt.Color(255, 255, 255));
        txtInventoryID.setOpaque(false);
        txtInventoryID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInventoryIDActionPerformed(evt);
            }
        });
        txtInventoryID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInventoryIDKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtInventoryIDKeyReleased(evt);
            }
        });
        add(txtInventoryID);
        txtInventoryID.setBounds(260, 130, 180, 30);

        txtInventoryName.setBackground(new Color(0,0,0,0f));
        txtInventoryName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtInventoryName.setForeground(new java.awt.Color(255, 255, 255));
        txtInventoryName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtInventoryName.setAutoscrolls(false);
        txtInventoryName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtInventoryName.setCaretColor(new java.awt.Color(255, 255, 255));
        txtInventoryName.setOpaque(false);
        txtInventoryName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInventoryNameActionPerformed(evt);
            }
        });
        txtInventoryName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInventoryNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtInventoryNameKeyReleased(evt);
            }
        });
        add(txtInventoryName);
        txtInventoryName.setBounds(260, 180, 180, 30);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText(":");
        add(jLabel16);
        jLabel16.setBounds(230, 180, 20, 30);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Inventory Name");
        add(jLabel20);
        jLabel20.setBounds(70, 180, 140, 30);

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Brand Name");
        add(jLabel21);
        jLabel21.setBounds(70, 230, 150, 30);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText(":");
        add(jLabel17);
        jLabel17.setBounds(230, 230, 20, 30);

        txtBrandName.setBackground(new Color(0,0,0,0f));
        txtBrandName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtBrandName.setForeground(new java.awt.Color(255, 255, 255));
        txtBrandName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBrandName.setAutoscrolls(false);
        txtBrandName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtBrandName.setCaretColor(new java.awt.Color(255, 255, 255));
        txtBrandName.setOpaque(false);
        txtBrandName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrandNameActionPerformed(evt);
            }
        });
        txtBrandName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBrandNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBrandNameKeyReleased(evt);
            }
        });
        add(txtBrandName);
        txtBrandName.setBounds(260, 230, 180, 30);

        txtQty.setBackground(new Color(0,0,0,0f));
        txtQty.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtQty.setForeground(new java.awt.Color(255, 255, 255));
        txtQty.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtQty.setAutoscrolls(false);
        txtQty.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtQty.setCaretColor(new java.awt.Color(255, 255, 255));
        txtQty.setOpaque(false);
        txtQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtyActionPerformed(evt);
            }
        });
        txtQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQtyKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQtyKeyReleased(evt);
            }
        });
        add(txtQty);
        txtQty.setBounds(260, 280, 180, 30);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText(":");
        add(jLabel18);
        jLabel18.setBounds(230, 280, 20, 30);

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Qty");
        add(jLabel22);
        jLabel22.setBounds(70, 280, 140, 30);

        lblSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/search.png"))); // NOI18N
        lblSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSearchMouseExited(evt);
            }
        });
        add(lblSearch);
        lblSearch.setBounds(440, 120, 50, 50);

        lblNewInventory.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblNewInventory.setForeground(new java.awt.Color(255, 255, 255));
        lblNewInventory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNewInventory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/add.png"))); // NOI18N
        lblNewInventory.setText("New Inventory");
        lblNewInventory.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblNewInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNewInventoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNewInventoryMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblNewInventoryMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNewInventoryMouseClicked(evt);
            }
        });
        add(lblNewInventory);
        lblNewInventory.setBounds(70, 90, 220, 30);

        lblModify.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblModify.setForeground(new java.awt.Color(255, 255, 255));
        lblModify.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModify.setText("Modify");
        lblModify.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblModify.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblModifyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblModifyMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblModifyMouseClicked(evt);
            }
        });
        add(lblModify);
        lblModify.setBounds(350, 390, 100, 30);

        lblRemove.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblRemove.setForeground(new java.awt.Color(255, 255, 255));
        lblRemove.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRemove.setText("Remove");
        lblRemove.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRemoveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRemoveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRemoveMouseExited(evt);
            }
        });
        add(lblRemove);
        lblRemove.setBounds(800, 500, 100, 30);

        lblSave.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblSave.setForeground(new java.awt.Color(255, 255, 255));
        lblSave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/save.png"))); // NOI18N
        lblSave.setText("Save");
        lblSave.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblSave.setEnabled(false);
        lblSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSaveMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSaveMouseClicked(evt);
            }
        });
        add(lblSave);
        lblSave.setBounds(350, 330, 90, 40);

        tblInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Inventory ID", " Inventory Name", "    Brand Name", "             QTY"
            }
        ));
        tblInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInventoryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblInventory);

        add(jScrollPane1);
        jScrollPane1.setBounds(500, 180, 410, 290);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Count of All Inventory :-");
        add(jLabel5);
        jLabel5.setBounds(500, 490, 200, 20);

        lblCount.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblCount.setForeground(new java.awt.Color(255, 255, 255));
        lblCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCount.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        add(lblCount);
        lblCount.setBounds(700, 490, 50, 20);

        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(255, 153, 51), new java.awt.Color(255, 153, 51), new java.awt.Color(255, 153, 51), new java.awt.Color(255, 153, 51)));
        add(jLabel3);
        jLabel3.setBounds(20, 70, 910, 490);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/Untitled-1.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 3));
        add(jLabel1);
        jLabel1.setBounds(0, 0, 970, 570);
    }// </editor-fold>//GEN-END:initComponents

    private void txtInventoryIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInventoryIDActionPerformed
        txtInventoryName.requestFocus();
    }//GEN-LAST:event_txtInventoryIDActionPerformed

    private void txtInventoryIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInventoryIDKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInventoryIDKeyPressed

    private void txtInventoryIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInventoryIDKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInventoryIDKeyReleased

    private void txtInventoryNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInventoryNameActionPerformed
        txtBrandName.requestFocus();
    }//GEN-LAST:event_txtInventoryNameActionPerformed

    private void txtInventoryNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInventoryNameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInventoryNameKeyPressed

    private void txtInventoryNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInventoryNameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInventoryNameKeyReleased

    private void txtBrandNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrandNameActionPerformed
        txtQty.requestFocus();
    }//GEN-LAST:event_txtBrandNameActionPerformed

    private void txtBrandNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBrandNameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrandNameKeyPressed

    private void txtBrandNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBrandNameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrandNameKeyReleased

    private void txtQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtyActionPerformed

    private void txtQtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtyKeyPressed

    private void txtQtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyKeyReleased
        checkText();
    }//GEN-LAST:event_txtQtyKeyReleased

    private void lblNewInventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewInventoryMouseClicked
        clearAllTextFileds();
        getInventoryID();
        txtInventoryID.requestFocusInWindow();
    }//GEN-LAST:event_lblNewInventoryMouseClicked

    private void lblNewInventoryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewInventoryMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNewInventoryMousePressed

    private void lblSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaveMouseClicked
        
        try {
            InventoryDTO inventory = new InventoryDTO(txtInventoryID.getText(),
                    txtInventoryName.getText(),
                    txtBrandName.getText(),
                    Integer.parseInt(txtQty.getText()));
            boolean result = ManageInventoryController.addInventory(inventory);
            
            if (result) {
                JOptionPane.showMessageDialog(this, "Inventory has been successfully Saved.");
                loadAllInventory();
                getInventoryID();
                lblSave.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(this, "Inventory hasn't been Saved due to some error");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        clearAllTextFileds();
        txtInventoryName.requestFocus();
    }//GEN-LAST:event_lblSaveMouseClicked

    private void lblRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRemoveMouseClicked
        InventoryDTO inventory = new InventoryDTO(txtInventoryID.getText(),
                txtInventoryName.getText(),
                txtBrandName.getText(),
                Integer.parseInt(txtQty.getText()));
        try {
            boolean result = ManageInventoryController.deleteInventory(inventory);
            
            if (result) {
                JOptionPane.showMessageDialog(this, "Inventory has been successfully deleted.");
                loadAllInventory();
            } else {
                JOptionPane.showMessageDialog(this, "Inventory hasn't been deleted due to some error");
            }
            
        } catch (Exception ex) {
            Logger.getLogger(ManageInventoryPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        clearAllTextFileds();
        txtInventoryID.requestFocus();
    }//GEN-LAST:event_lblRemoveMouseClicked

    private void lblModifyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModifyMouseClicked
        try {
            InventoryDTO inventory = new InventoryDTO(
                    txtInventoryID.getText(),
                    txtInventoryName.getText(),
                    txtBrandName.getText(),
                    Integer.parseInt(txtQty.getText())
            );
            
            boolean updateInventory = ManageInventoryController.updateInventory(inventory);
            
            if (updateInventory) {
                JOptionPane.showMessageDialog(this, "Modify Success..");
                loadAllInventory();
                clearAllTextFileds();
                txtInventoryID.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Modify Error..");
            }
        } catch (Exception ex) {
            Logger.getLogger(ManageInventoryPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblModifyMouseClicked

    private void tblInventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInventoryMouseClicked

    }//GEN-LAST:event_tblInventoryMouseClicked

    private void lblNewInventoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewInventoryMouseEntered
        lblNewInventory.setSize(230, 40);
    }//GEN-LAST:event_lblNewInventoryMouseEntered

    private void lblNewInventoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewInventoryMouseExited
        lblNewInventory.setSize(220, 30);
    }//GEN-LAST:event_lblNewInventoryMouseExited

    private void lblSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaveMouseEntered
        lblSave.setSize(100, 50);
    }//GEN-LAST:event_lblSaveMouseEntered

    private void lblSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaveMouseExited
        lblSave.setSize(100, 40);
    }//GEN-LAST:event_lblSaveMouseExited

    private void lblModifyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModifyMouseEntered
        lblModify.setSize(120, 40);
    }//GEN-LAST:event_lblModifyMouseEntered

    private void lblModifyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModifyMouseExited
        lblModify.setSize(100, 30);
    }//GEN-LAST:event_lblModifyMouseExited

    private void lblRemoveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRemoveMouseEntered
        lblRemove.setSize(120, 40);
    }//GEN-LAST:event_lblRemoveMouseEntered

    private void lblRemoveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRemoveMouseExited
        lblRemove.setSize(100, 30);
    }//GEN-LAST:event_lblRemoveMouseExited

    private void lblSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchMouseClicked
        try {
            InventoryDTO inventoryDTO = ManageInventoryController.searchInventory(txtInventoryID.getText());
            txtInventoryName.setText(inventoryDTO.getInventoryName());
            txtBrandName.setText(inventoryDTO.getBrandName());
            txtQty.setText(Integer.toString(inventoryDTO.getQty()));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "No Inventory");
        }
        

    }//GEN-LAST:event_lblSearchMouseClicked

    private void lblSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchMouseEntered
        lblSearch.setSize(60, 60);
    }//GEN-LAST:event_lblSearchMouseEntered

    private void lblSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchMouseExited
        lblSearch.setSize(50, 50);
    }//GEN-LAST:event_lblSearchMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCount;
    private javax.swing.JLabel lblModify;
    private javax.swing.JLabel lblNewInventory;
    private javax.swing.JLabel lblRemove;
    private javax.swing.JLabel lblSave;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JTable tblInventory;
    private javax.swing.JTextField txtBrandName;
    private javax.swing.JTextField txtInventoryID;
    private javax.swing.JTextField txtInventoryName;
    private javax.swing.JTextField txtQty;
    // End of variables declaration//GEN-END:variables

    private void clearAllTextFileds() {
        //txtInventoryID.setText("");
        txtInventoryName.setText("");
        txtBrandName.setText("");
        txtQty.setText("");
    }
    
    private void loadAllInventory() {
        try {
            ArrayList<InventoryDTO> allInventories = ManageInventoryController.getAllInventory();
            
            DefaultTableModel dtm = (DefaultTableModel) tblInventory.getModel();
            
            dtm.setRowCount(0);
            
            if (allInventories != null) {
                
                for (InventoryDTO inventory : allInventories) {
                    
                    Object[] rowData = {
                        inventory.getInventoryID(),
                        inventory.getInventoryName(),
                        inventory.getBrandName(),
                        inventory.getQty()
                    };
                    
                    dtm.addRow(rowData);
                    
                }
                
            }
            lblCount.setText(Integer.toString(tblInventory.getRowCount()));
            
        } catch (Exception ex) {
            Logger.getLogger(ManageInventoryPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void buttonDisable() {
        lblRemove.setEnabled(false);
    }
    
    private void checkText() {
        String text = txtQty.getText();
        String brand = txtBrandName.getText();
        String invtId = txtInventoryID.getText();
        String intName = txtInventoryName.getText();
        if ((text.equals("")) && (brand.equals("")) && (intName.equals("")) && (invtId.equals(""))) {
            lblSave.setEnabled(false);
        } else {
            lblSave.setEnabled(true);
        }
    }
    
    private void getInventoryID() {
        String newID;
        try {
            newID = IDGenarator.getNewID("inventory","Inventory_ID", "Inv");
            txtInventoryID.setText(newID);

        } catch (SQLException ex) {
            Logger.getLogger(RegMemberPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegMemberPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
