/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.mygymmanagement.view.panel;

import java.awt.Color;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import lk.ijse.mygymmanagement.controller.MemberController;
import lk.ijse.mygymmanagement.controller.RegMemberController;
import lk.ijse.mygymmanagement.controller.ViewAllAttendanceController;
import lk.ijse.mygymmanagement.dao.custom.impl.ViewAllAttendanceDAOImpl;
import lk.ijse.mygymmanagementsystem.core.dto.MemeberDTO;
import lk.ijse.mygymmanagementsystem.core.dto.RegistrationDTO;
import lk.ijse.mygymmanagementsystem.core.dto.ViewAllAttendanceDTO;
import lk.ijse.mygymmanagementsystem.view.HomePage;

/**
 *
 * @author Chinthaka
 */
public class MemberAttendance extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public MemberAttendance() {
        initComponents();
        loadAllMemberRegNo();
        loadAllAttendenceForMember();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cmbMemberRegNo = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        TxtMemberName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblmeAttend = new javax.swing.JTable();
        txtMemberID = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(970, 570));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Stencil Std", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/themify_e61d(0)_48.png"))); // NOI18N
        jLabel2.setText("Member Attendance..");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 380, 50);

        lblBack.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblBack.setForeground(new java.awt.Color(255, 255, 255));
        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/back.png"))); // NOI18N
        lblBack.setText("BACK");
        lblBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });
        add(lblBack);
        lblBack.setBounds(840, 10, 120, 50);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Member Reg.No");
        add(jLabel19);
        jLabel19.setBounds(30, 90, 140, 30);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText(":");
        add(jLabel15);
        jLabel15.setBounds(170, 90, 20, 30);

        cmbMemberRegNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbMemberRegNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        cmbMemberRegNo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbMemberRegNoItemStateChanged(evt);
            }
        });
        cmbMemberRegNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMemberRegNoActionPerformed(evt);
            }
        });
        add(cmbMemberRegNo);
        cmbMemberRegNo.setBounds(200, 90, 180, 30);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Member Name");
        add(jLabel18);
        jLabel18.setBounds(30, 130, 140, 30);

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText(":");
        add(jLabel29);
        jLabel29.setBounds(170, 130, 20, 30);

        TxtMemberName.setBackground(new Color(0,0,0,0f));
        TxtMemberName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        TxtMemberName.setForeground(new java.awt.Color(255, 255, 255));
        TxtMemberName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtMemberName.setAutoscrolls(false);
        TxtMemberName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        TxtMemberName.setCaretColor(new java.awt.Color(255, 255, 255));
        TxtMemberName.setOpaque(false);
        TxtMemberName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtMemberNameActionPerformed(evt);
            }
        });
        TxtMemberName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtMemberNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtMemberNameKeyReleased(evt);
            }
        });
        add(TxtMemberName);
        TxtMemberName.setBounds(200, 130, 180, 30);

        tblmeAttend.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Member RegNo", "Member Name", "Date", "Month"
            }
        ));
        jScrollPane1.setViewportView(tblmeAttend);

        add(jScrollPane1);
        jScrollPane1.setBounds(202, 190, 620, 330);

        txtMemberID.setBackground(new Color(0,0,0,0f));
        txtMemberID.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtMemberID.setForeground(new java.awt.Color(255, 255, 255));
        txtMemberID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMemberID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtMemberID.setOpaque(false);
        add(txtMemberID);
        txtMemberID.setBounds(720, 90, 180, 30);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Member ID");
        add(jLabel20);
        jLabel20.setBounds(540, 90, 140, 30);

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText(":");
        add(jLabel30);
        jLabel30.setBounds(680, 90, 20, 30);

        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(255, 153, 51), new java.awt.Color(255, 153, 51), new java.awt.Color(255, 153, 51), new java.awt.Color(255, 153, 51)));
        add(jLabel3);
        jLabel3.setBounds(20, 70, 910, 490);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/Untitled-1.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 3));
        add(jLabel1);
        jLabel1.setBounds(0, 0, 970, 570);
    }// </editor-fold>//GEN-END:initComponents

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        AttendancePanel att = new AttendancePanel();
        JPanel middlePanel = HomePage.getMainPanel();
        middlePanel.removeAll();
        att.setSize(middlePanel.getSize());
        middlePanel.add(att);
        middlePanel.revalidate();
        middlePanel.repaint();
    }//GEN-LAST:event_lblBackMouseClicked

    private void cmbMemberRegNoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbMemberRegNoItemStateChanged
        try {
            RegistrationDTO registrationDTO = RegMemberController.searchRegistration((String) cmbMemberRegNo.getSelectedItem());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());

        }
        searchMember();
        loadAllAttendenceForMember();
    }//GEN-LAST:event_cmbMemberRegNoItemStateChanged

    private void cmbMemberRegNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMemberRegNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMemberRegNoActionPerformed

    private void TxtMemberNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtMemberNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtMemberNameActionPerformed

    private void TxtMemberNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtMemberNameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtMemberNameKeyPressed

    private void TxtMemberNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtMemberNameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtMemberNameKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtMemberName;
    private javax.swing.JComboBox<String> cmbMemberRegNo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBack;
    private javax.swing.JTable tblmeAttend;
    private javax.swing.JTextField txtMemberID;
    // End of variables declaration//GEN-END:variables

    private void loadAllMemberRegNo() {
        try {
            ArrayList<RegistrationDTO> RList = RegMemberController.getAllRegistration();
            for (RegistrationDTO registrationDTO : RList) {
                cmbMemberRegNo.addItem(registrationDTO.getMemberRegNo());
            }
        } catch (Exception ex) {
            Logger.getLogger(AttendancePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void searchMember() {
        String regisID = (String) cmbMemberRegNo.getSelectedItem();
        try {
            RegistrationDTO registrationDTO = RegMemberController.searchRegistration(regisID);
            if (registrationDTO != null) {
                String memberID = registrationDTO.getMemberID();
                MemeberDTO dTO = MemberController.searchMember(memberID);
                if (dTO != null) {
                    TxtMemberName.setText(dTO.getMemberName());
                    txtMemberID.setText(dTO.getMemberID());
                }
            } else {
                JOptionPane.showMessageDialog(this, "There is no Member for this registration ID.....");
            }
        } catch (Exception ex) {
            Logger.getLogger(PaymentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadAllAttendenceForMember() {
        DefaultTableModel defaultTableModel = (DefaultTableModel) tblmeAttend.getModel();
        try {

            //
            String regisID = txtMemberID.getText();
            ArrayList<ViewAllAttendanceDTO> RList = ViewAllAttendanceDAOImpl.getAllss(regisID);
            defaultTableModel.setRowCount(0);
            if (RList != null) {

                for (ViewAllAttendanceDTO registrationDTO : RList) {

                    Object[] rowData = {registrationDTO.getRegisid(), registrationDTO.getMemberid(), registrationDTO.getMembername(),
                        registrationDTO.getAttenDate()};
                    defaultTableModel.addRow(rowData);

                }
            }
        } catch (Exception ex) {
            Logger.getLogger(AttendancePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
