/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.mygymmanagement.view.panel;

import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.mygymmanagement.controller.MemberController;
import lk.ijse.mygymmanagement.controller.PaymentChargeController;
import lk.ijse.mygymmanagement.controller.PaymentController;
import lk.ijse.mygymmanagement.controller.RegMemberController;
import lk.ijse.mygymmanagementsystem.commmon.IDGenarator;
import lk.ijse.mygymmanagementsystem.core.dto.MemeberDTO;
import lk.ijse.mygymmanagementsystem.core.dto.PaymentChargeDTO;
import lk.ijse.mygymmanagementsystem.core.dto.PaymentDTO;
import lk.ijse.mygymmanagementsystem.core.dto.RegistrationDTO;

/**
 *
 * @author Chinthaka
 */
public class PaymentPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public PaymentPanel() {
        initComponents();
        loadAllMemberRegNo();
        loadAllPaymentCharge();
        loadAllPaymentTable();
        getPaymentID();

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtNIC = new javax.swing.JTextField();
        txtCash = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPayment = new javax.swing.JTable();
        lblSubmit = new javax.swing.JLabel();
        txtPaymentID = new javax.swing.JTextField();
        txtCharge = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtBalance = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        cmbMemberReg = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        cmbPaymentTypeID = new javax.swing.JComboBox<>();
        txtPaymentType = new javax.swing.JTextField();
        DatePDate = new org.jdesktop.swingx.JXDatePicker();
        jLabel1 = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(970, 570));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Stencil Std", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/Payment.png"))); // NOI18N
        jLabel2.setText("Payment..");
        add(jLabel2);
        jLabel2.setBounds(10, 10, 220, 50);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Member NIC");
        add(jLabel13);
        jLabel13.setBounds(670, 80, 140, 30);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText(":");
        add(jLabel14);
        jLabel14.setBounds(190, 170, 20, 30);

        txtNIC.setBackground(new Color(0,0,0,0f));
        txtNIC.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtNIC.setForeground(new java.awt.Color(255, 255, 255));
        txtNIC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNIC.setAutoscrolls(false);
        txtNIC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtNIC.setCaretColor(new java.awt.Color(255, 255, 255));
        txtNIC.setOpaque(false);
        txtNIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNICActionPerformed(evt);
            }
        });
        txtNIC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNICKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNICKeyReleased(evt);
            }
        });
        add(txtNIC);
        txtNIC.setBounds(630, 110, 230, 30);

        txtCash.setBackground(new Color(0,0,0,0f));
        txtCash.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtCash.setForeground(new java.awt.Color(255, 255, 255));
        txtCash.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCash.setAutoscrolls(false);
        txtCash.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtCash.setCaretColor(new java.awt.Color(255, 255, 255));
        txtCash.setOpaque(false);
        txtCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCashActionPerformed(evt);
            }
        });
        txtCash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCashKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCashKeyReleased(evt);
            }
        });
        add(txtCash);
        txtCash.setBounds(220, 410, 230, 30);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Member Reg. No");
        add(jLabel16);
        jLabel16.setBounds(160, 80, 140, 30);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Payment ID");
        add(jLabel17);
        jLabel17.setBounds(40, 170, 140, 30);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Full Name");
        add(jLabel18);
        jLabel18.setBounds(40, 210, 140, 30);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Payment Date");
        add(jLabel19);
        jLabel19.setBounds(40, 250, 140, 30);

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Charge");
        add(jLabel22);
        jLabel22.setBounds(40, 370, 140, 30);

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Cash");
        add(jLabel23);
        jLabel23.setBounds(40, 410, 140, 30);

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText(":");
        add(jLabel26);
        jLabel26.setBounds(190, 410, 20, 30);

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText(":");
        add(jLabel24);
        jLabel24.setBounds(190, 370, 20, 30);

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText(":");
        add(jLabel28);
        jLabel28.setBounds(190, 250, 20, 30);

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText(":");
        add(jLabel29);
        jLabel29.setBounds(190, 210, 20, 30);

        tblPayment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Member RegNO", "Name", "Date  ", "Amount"
            }
        ));
        jScrollPane1.setViewportView(tblPayment);

        add(jScrollPane1);
        jScrollPane1.setBounds(480, 170, 470, 310);

        lblSubmit.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblSubmit.setForeground(new java.awt.Color(255, 255, 255));
        lblSubmit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubmit.setText("Submit");
        lblSubmit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSubmitMouseClicked(evt);
            }
        });
        add(lblSubmit);
        lblSubmit.setBounds(330, 510, 120, 34);

        txtPaymentID.setBackground(new Color(0,0,0,0f));
        txtPaymentID.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtPaymentID.setForeground(new java.awt.Color(255, 255, 255));
        txtPaymentID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPaymentID.setAutoscrolls(false);
        txtPaymentID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtPaymentID.setCaretColor(new java.awt.Color(255, 255, 255));
        txtPaymentID.setOpaque(false);
        txtPaymentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaymentIDActionPerformed(evt);
            }
        });
        txtPaymentID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPaymentIDKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPaymentIDKeyReleased(evt);
            }
        });
        add(txtPaymentID);
        txtPaymentID.setBounds(220, 170, 230, 30);

        txtCharge.setBackground(new Color(0,0,0,0f));
        txtCharge.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtCharge.setForeground(new java.awt.Color(255, 255, 255));
        txtCharge.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCharge.setAutoscrolls(false);
        txtCharge.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtCharge.setCaretColor(new java.awt.Color(255, 255, 255));
        txtCharge.setOpaque(false);
        txtCharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChargeActionPerformed(evt);
            }
        });
        txtCharge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtChargeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtChargeKeyReleased(evt);
            }
        });
        add(txtCharge);
        txtCharge.setBounds(220, 370, 230, 30);

        txtName.setBackground(new Color(0,0,0,0f));
        txtName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        txtName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtName.setAutoscrolls(false);
        txtName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtName.setCaretColor(new java.awt.Color(255, 255, 255));
        txtName.setOpaque(false);
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });
        add(txtName);
        txtName.setBounds(220, 210, 230, 30);

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Balance");
        add(jLabel25);
        jLabel25.setBounds(40, 450, 140, 30);

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText(":");
        add(jLabel30);
        jLabel30.setBounds(190, 450, 20, 30);

        txtBalance.setBackground(new Color(0,0,0,0f));
        txtBalance.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtBalance.setForeground(new java.awt.Color(255, 255, 255));
        txtBalance.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBalance.setAutoscrolls(false);
        txtBalance.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtBalance.setCaretColor(new java.awt.Color(255, 255, 255));
        txtBalance.setOpaque(false);
        txtBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBalanceActionPerformed(evt);
            }
        });
        txtBalance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBalanceKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBalanceKeyReleased(evt);
            }
        });
        add(txtBalance);
        txtBalance.setBounds(220, 450, 230, 30);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Payment Type");
        add(jLabel20);
        jLabel20.setBounds(40, 330, 140, 30);

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText(":");
        add(jLabel32);
        jLabel32.setBounds(190, 330, 20, 30);

        cmbMemberReg.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cmbMemberReg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        cmbMemberReg.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbMemberRegItemStateChanged(evt);
            }
        });
        add(cmbMemberReg);
        cmbMemberReg.setBounds(140, 110, 170, 30);

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Payment Charge ID");
        add(jLabel27);
        jLabel27.setBounds(40, 290, 160, 30);

        jLabel33.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText(":");
        add(jLabel33);
        jLabel33.setBounds(190, 290, 20, 30);

        cmbPaymentTypeID.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cmbPaymentTypeID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        cmbPaymentTypeID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPaymentTypeIDItemStateChanged(evt);
            }
        });
        add(cmbPaymentTypeID);
        cmbPaymentTypeID.setBounds(220, 290, 230, 30);

        txtPaymentType.setBackground(new Color(0,0,0,0f));
        txtPaymentType.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtPaymentType.setForeground(new java.awt.Color(255, 255, 255));
        txtPaymentType.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPaymentType.setAutoscrolls(false);
        txtPaymentType.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtPaymentType.setCaretColor(new java.awt.Color(255, 255, 255));
        txtPaymentType.setOpaque(false);
        txtPaymentType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaymentTypeActionPerformed(evt);
            }
        });
        txtPaymentType.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPaymentTypeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPaymentTypeKeyReleased(evt);
            }
        });
        add(txtPaymentType);
        txtPaymentType.setBounds(220, 330, 230, 30);

        DatePDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        add(DatePDate);
        DatePDate.setBounds(220, 250, 230, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/Untitled-1.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 3));
        add(jLabel1);
        jLabel1.setBounds(0, 0, 970, 570);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNICActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNICActionPerformed

    private void txtNICKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNICKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNICKeyPressed

    private void txtNICKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNICKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNICKeyReleased

    private void txtCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCashActionPerformed
        Double x = Double.parseDouble(txtCharge.getText());
        Double y = Double.parseDouble(txtCash.getText());
        Double z = y - x;
        txtBalance.setText(Double.toString(z));

    }//GEN-LAST:event_txtCashActionPerformed

    private void txtCashKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCashKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCashKeyPressed

    private void txtCashKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCashKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCashKeyReleased

    private void txtPaymentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaymentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaymentIDActionPerformed

    private void txtPaymentIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaymentIDKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaymentIDKeyPressed

    private void txtPaymentIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaymentIDKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaymentIDKeyReleased

    private void txtChargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChargeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChargeActionPerformed

    private void txtChargeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChargeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChargeKeyPressed

    private void txtChargeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChargeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChargeKeyReleased

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameKeyPressed

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameKeyReleased

    private void txtBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBalanceActionPerformed

    private void txtBalanceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBalanceKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBalanceKeyPressed

    private void txtBalanceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBalanceKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBalanceKeyReleased

    private void lblSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSubmitMouseClicked


        try {
            PaymentDTO payment = new PaymentDTO(
                    txtPaymentID.getText(),
                    cmbMemberReg.getSelectedItem().toString(),
                    txtNIC.getText(),
                    txtName.getText(),
                    DatePDate.getDate().toString(),
                    cmbPaymentTypeID.getSelectedItem().toString(),
                    txtPaymentType.getText(),
                    txtCharge.getText(),
                    txtCash.getText(),
                    txtBalance.getText()
            );
            boolean result = PaymentController.addPayment(payment);

            if (result) {
                JOptionPane.showMessageDialog(this, "Payment has been successfully Saved.");
                loadAllPaymentTable();

            } else {
                JOptionPane.showMessageDialog(this, "Payment hasn't been Saved due to some error");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        clearAllTextFileds();
        getPaymentID();
        cmbMemberReg.requestFocus();
    }//GEN-LAST:event_lblSubmitMouseClicked

    private void cmbMemberRegItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbMemberRegItemStateChanged
        try {
            RegistrationDTO registrationDTO = RegMemberController.searchRegistration((String) cmbMemberReg.getSelectedItem());
        } catch (Exception ex) {
            Logger.getLogger(PaymentPanel.class.getName()).log(Level.SEVERE, null, ex);

        }
        searchMember();
    }//GEN-LAST:event_cmbMemberRegItemStateChanged

    private void txtPaymentTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaymentTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaymentTypeActionPerformed

    private void txtPaymentTypeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaymentTypeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaymentTypeKeyPressed

    private void txtPaymentTypeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaymentTypeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaymentTypeKeyReleased

    private void cmbPaymentTypeIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPaymentTypeIDItemStateChanged
        try {
            PaymentChargeDTO paymentChargeDTO = PaymentChargeController.searchCharge((String) cmbPaymentTypeID.getSelectedItem());
        } catch (Exception ex) {
            Logger.getLogger(PaymentPanel.class.getName()).log(Level.SEVERE, null, ex);

        }
        searchCharge();
    }//GEN-LAST:event_cmbPaymentTypeIDItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker DatePDate;
    private javax.swing.JComboBox<String> cmbMemberReg;
    private javax.swing.JComboBox<String> cmbPaymentTypeID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSubmit;
    private javax.swing.JTable tblPayment;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtCash;
    private javax.swing.JTextField txtCharge;
    private javax.swing.JTextField txtNIC;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPaymentID;
    private javax.swing.JTextField txtPaymentType;
    // End of variables declaration//GEN-END:variables

    private void loadAllMemberRegNo() {
        try {
            ArrayList<RegistrationDTO> RList = RegMemberController.getAllRegistration();
            if(RList!=null){
                for (RegistrationDTO registrationDTO : RList) {
                cmbMemberReg.addItem(registrationDTO.getMemberRegNo());
            }
            }
            
        } catch (Exception ex) {
            Logger.getLogger(PaymentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void searchMember() {
        String regisID = (String) cmbMemberReg.getSelectedItem();
        try {
            RegistrationDTO registrationDTO = RegMemberController.searchRegistration(regisID);
            if (registrationDTO != null) {
                String memberID=registrationDTO.getMemberID();
                MemeberDTO dTO = MemberController.searchMember(memberID);
                if (dTO != null) {
                    txtNIC.setText(dTO.getNic());
                    txtName.setText(dTO.getMemberName());
                }
            } 
        } catch (Exception ex) {
            Logger.getLogger(PaymentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadAllPaymentCharge() {
        try {
            ArrayList<PaymentChargeDTO> charge = PaymentChargeController.getAllCharge();
            for (PaymentChargeDTO paymentChargeDTO : charge) {
                cmbPaymentTypeID.addItem(paymentChargeDTO.getPaymentTypeID());
            }
        } catch (Exception ex) {
            Logger.getLogger(PaymentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void searchCharge() {
        if( cmbPaymentTypeID.getSelectedItem()==null){return;}
        String PId = cmbPaymentTypeID.getSelectedItem().toString();
        try {
            PaymentChargeDTO paymentChargeDTO = PaymentChargeController.searchCharge(PId);
            if (paymentChargeDTO != null) {
                txtPaymentType.setText(paymentChargeDTO.getPaymentType());
                txtCharge.setText(paymentChargeDTO.getCharge());
            }
        } catch (Exception ex) {
            Logger.getLogger(PaymentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadAllPaymentTable() {
        try {
            ArrayList<PaymentDTO> allPayment = PaymentController.getAllPayment();

            DefaultTableModel dtm = (DefaultTableModel) tblPayment.getModel();

            dtm.setRowCount(0);

            if (allPayment != null) {

                for (PaymentDTO payment : allPayment) {

                    Object[] rowData = {
                        payment.getMemberRegNo(),
                        payment.getMemberName(),
                        payment.getDate(),
                        payment.getCharge()
                    };

                    dtm.addRow(rowData);

                }

            }

        } catch (Exception ex) {
            Logger.getLogger(ManageInventoryPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void clearAllTextFileds() {
        cmbMemberReg.setSelectedItem(null);
        txtNIC.setText("");
        //txtPaymentID.setText("");
        txtName.setText("");
        DatePDate.setDate(null);
        cmbPaymentTypeID.setSelectedItem(null);
        txtPaymentType.setText("");
        txtCharge.setText("");
        txtCash.setText("");
        txtBalance.setText("");
    }
    
    private void getPaymentID() {
        String newID;
        try {
            newID = IDGenarator.getNewID("payment","Payment_ID", "P");
            txtPaymentID.setText(newID);

        } catch (SQLException ex) {
            Logger.getLogger(RegMemberPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegMemberPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
