/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.mygymmanagement.view.panel;

import java.awt.Color;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import lk.ijse.mygymmanagement.controller.RegMemberController;
import lk.ijse.mygymmanagementsystem.commmon.IDGenarator;
import lk.ijse.mygymmanagementsystem.commmon.Validation;
import lk.ijse.mygymmanagementsystem.core.dto.MemeberDTO;
import lk.ijse.mygymmanagementsystem.core.dto.RegistrationDTO;
import lk.ijse.mygymmanagementsystem.view.HomePage;

/**
 *
 * @author Chinthaka
 */
public class RegMemberPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    
    
    
    public RegMemberPanel() {
        initComponents();
        getRegistrationID() ;
        getMemID();
        

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMemberName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtOccupation = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtDOB = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        jLabel30 = new javax.swing.JLabel();
        txtMemberID = new javax.swing.JTextField();
        txtEmrContact = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtNIC = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        txtMemberRegNo = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lblMen = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtHeight = new javax.swing.JTextField();
        txtWeight = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        cmbGender = new javax.swing.JComboBox<>();
        lblSave = new javax.swing.JLabel();
        lblSave1 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        datePicRegDate = new org.jdesktop.swingx.JXDatePicker();
        jLabel1 = new javax.swing.JLabel();
        txtDOB1 = new javax.swing.JTextField();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(970, 570));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Stencil Std", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/regMember.png"))); // NOI18N
        jLabel2.setText("Member Registration..");
        add(jLabel2);
        jLabel2.setBounds(10, 10, 380, 50);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Member ID");
        add(jLabel4);
        jLabel4.setBounds(50, 130, 130, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Member Name");
        add(jLabel5);
        jLabel5.setBounds(50, 170, 120, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Occupation");
        add(jLabel6);
        jLabel6.setBounds(50, 250, 120, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("D.O.B.");
        add(jLabel7);
        jLabel7.setBounds(50, 400, 120, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText(":");
        add(jLabel8);
        jLabel8.setBounds(180, 130, 20, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText(":");
        add(jLabel9);
        jLabel9.setBounds(180, 170, 20, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText(":");
        add(jLabel10);
        jLabel10.setBounds(180, 250, 20, 30);

        txtMemberName.setBackground(new Color(0,0,0,0f));
        txtMemberName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtMemberName.setForeground(new java.awt.Color(255, 255, 255));
        txtMemberName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMemberName.setAutoscrolls(false);
        txtMemberName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtMemberName.setCaretColor(new java.awt.Color(255, 255, 255));
        txtMemberName.setOpaque(false);
        txtMemberName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMemberNameActionPerformed(evt);
            }
        });
        txtMemberName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMemberNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMemberNameKeyReleased(evt);
            }
        });
        add(txtMemberName);
        txtMemberName.setBounds(210, 170, 230, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Address");
        add(jLabel11);
        jLabel11.setBounds(50, 290, 120, 30);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText(":");
        add(jLabel12);
        jLabel12.setBounds(180, 290, 20, 30);

        txtOccupation.setBackground(new Color(0,0,0,0f));
        txtOccupation.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtOccupation.setForeground(new java.awt.Color(255, 255, 255));
        txtOccupation.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtOccupation.setAutoscrolls(false);
        txtOccupation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtOccupation.setCaretColor(new java.awt.Color(255, 255, 255));
        txtOccupation.setOpaque(false);
        add(txtOccupation);
        txtOccupation.setBounds(210, 250, 230, 30);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Age");
        add(jLabel13);
        jLabel13.setBounds(50, 440, 120, 30);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText(":");
        add(jLabel14);
        jLabel14.setBounds(730, 210, 20, 30);

        txtEmail.setBackground(new Color(0,0,0,0f));
        txtEmail.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEmail.setAutoscrolls(false);
        txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtEmail.setCaretColor(new java.awt.Color(255, 255, 255));
        txtEmail.setOpaque(false);
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });
        add(txtEmail);
        txtEmail.setBounds(760, 210, 170, 30);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("E-mail");
        add(jLabel15);
        jLabel15.setBounds(560, 210, 120, 30);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText(":");
        add(jLabel16);
        jLabel16.setBounds(180, 400, 20, 30);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Emergency Contact");
        add(jLabel17);
        jLabel17.setBounds(560, 290, 160, 30);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText(":");
        add(jLabel18);
        jLabel18.setBounds(180, 440, 20, 30);

        txtDOB.setBackground(new Color(0,0,0,0f));
        txtDOB.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtDOB.setForeground(new java.awt.Color(255, 255, 255));
        txtDOB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDOB.setAutoscrolls(false);
        txtDOB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtDOB.setCaretColor(new java.awt.Color(255, 255, 255));
        txtDOB.setOpaque(false);
        txtDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDOBActionPerformed(evt);
            }
        });
        txtDOB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDOBKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDOBKeyReleased(evt);
            }
        });
        add(txtDOB);
        txtDOB.setBounds(210, 400, 230, 30);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Gender");
        add(jLabel19);
        jLabel19.setBounds(50, 480, 120, 30);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText(":");
        add(jLabel20);
        jLabel20.setBounds(180, 480, 20, 30);

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setOpaque(false);

        txtAddress.setBackground(new Color(0,0,0,0f));
        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        txtAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtAddress.setOpaque(false);
        jScrollPane2.setViewportView(txtAddress);

        add(jScrollPane2);
        jScrollPane2.setBounds(210, 290, 230, 96);

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText(":");
        add(jLabel30);
        jLabel30.setBounds(730, 290, 20, 30);

        txtMemberID.setBackground(new Color(0,0,0,0f));
        txtMemberID.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtMemberID.setForeground(new java.awt.Color(255, 255, 255));
        txtMemberID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMemberID.setAutoscrolls(false);
        txtMemberID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtMemberID.setCaretColor(new java.awt.Color(255, 255, 255));
        txtMemberID.setOpaque(false);
        txtMemberID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMemberIDActionPerformed(evt);
            }
        });
        txtMemberID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMemberIDKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMemberIDKeyReleased(evt);
            }
        });
        add(txtMemberID);
        txtMemberID.setBounds(210, 130, 230, 30);

        txtEmrContact.setBackground(new Color(0,0,0,0f));
        txtEmrContact.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtEmrContact.setForeground(new java.awt.Color(255, 255, 255));
        txtEmrContact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEmrContact.setAutoscrolls(false);
        txtEmrContact.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtEmrContact.setCaretColor(new java.awt.Color(255, 255, 255));
        txtEmrContact.setOpaque(false);
        txtEmrContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmrContactActionPerformed(evt);
            }
        });
        txtEmrContact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmrContactKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmrContactKeyReleased(evt);
            }
        });
        add(txtEmrContact);
        txtEmrContact.setBounds(760, 290, 170, 30);

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("NIC");
        add(jLabel21);
        jLabel21.setBounds(50, 210, 120, 30);

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText(":");
        add(jLabel23);
        jLabel23.setBounds(180, 210, 20, 30);

        txtNIC.setBackground(new Color(0,0,0,0f));
        txtNIC.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtNIC.setForeground(new java.awt.Color(255, 255, 255));
        txtNIC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNIC.setAutoscrolls(false);
        txtNIC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtNIC.setCaretColor(new java.awt.Color(255, 255, 255));
        txtNIC.setOpaque(false);
        txtNIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNICActionPerformed(evt);
            }
        });
        txtNIC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNICKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNICKeyReleased(evt);
            }
        });
        add(txtNIC);
        txtNIC.setBounds(210, 210, 230, 30);

        jLabel33.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Phone No");
        add(jLabel33);
        jLabel33.setBounds(560, 250, 110, 30);

        jLabel34.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText(":");
        add(jLabel34);
        jLabel34.setBounds(730, 250, 20, 30);

        txtPhone.setBackground(new Color(0,0,0,0f));
        txtPhone.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtPhone.setForeground(new java.awt.Color(255, 255, 255));
        txtPhone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPhone.setAutoscrolls(false);
        txtPhone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtPhone.setCaretColor(new java.awt.Color(255, 255, 255));
        txtPhone.setOpaque(false);
        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });
        txtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPhoneKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPhoneKeyReleased(evt);
            }
        });
        add(txtPhone);
        txtPhone.setBounds(760, 250, 170, 30);

        jLabel39.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Member Reg.No");
        add(jLabel39);
        jLabel39.setBounds(50, 90, 130, 30);

        jLabel40.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText(":");
        add(jLabel40);
        jLabel40.setBounds(180, 90, 20, 30);

        txtMemberRegNo.setBackground(new Color(0,0,0,0f));
        txtMemberRegNo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtMemberRegNo.setForeground(new java.awt.Color(255, 255, 255));
        txtMemberRegNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMemberRegNo.setAutoscrolls(false);
        txtMemberRegNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtMemberRegNo.setCaretColor(new java.awt.Color(255, 255, 255));
        txtMemberRegNo.setOpaque(false);
        txtMemberRegNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMemberRegNoActionPerformed(evt);
            }
        });
        txtMemberRegNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMemberRegNoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMemberRegNoKeyReleased(evt);
            }
        });
        add(txtMemberRegNo);
        txtMemberRegNo.setBounds(210, 90, 230, 30);

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Registration Date");
        add(jLabel32);
        jLabel32.setBounds(560, 90, 150, 30);

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText(":");
        add(jLabel22);
        jLabel22.setBounds(730, 90, 20, 30);

        lblMen.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblMen.setForeground(new java.awt.Color(255, 255, 255));
        lblMen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/next.png"))); // NOI18N
        lblMen.setText("Next");
        lblMen.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        lblMen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenMouseClicked(evt);
            }
        });
        add(lblMen);
        lblMen.setBounds(840, 510, 110, 40);

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Height");
        add(jLabel27);
        jLabel27.setBounds(560, 130, 120, 30);

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Weight");
        add(jLabel28);
        jLabel28.setBounds(560, 170, 120, 30);

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText(":");
        add(jLabel31);
        jLabel31.setBounds(730, 170, 20, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(":");
        add(jLabel3);
        jLabel3.setBounds(730, 130, 20, 30);

        txtHeight.setBackground(new Color(0,0,0,0f));
        txtHeight.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtHeight.setForeground(new java.awt.Color(255, 255, 255));
        txtHeight.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHeight.setAutoscrolls(false);
        txtHeight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtHeight.setCaretColor(new java.awt.Color(255, 255, 255));
        txtHeight.setOpaque(false);
        txtHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHeightActionPerformed(evt);
            }
        });
        txtHeight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHeightKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHeightKeyReleased(evt);
            }
        });
        add(txtHeight);
        txtHeight.setBounds(760, 130, 130, 30);

        txtWeight.setBackground(new Color(0,0,0,0f));
        txtWeight.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtWeight.setForeground(new java.awt.Color(255, 255, 255));
        txtWeight.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtWeight.setAutoscrolls(false);
        txtWeight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtWeight.setCaretColor(new java.awt.Color(255, 255, 255));
        txtWeight.setOpaque(false);
        txtWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWeightActionPerformed(evt);
            }
        });
        txtWeight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtWeightKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtWeightKeyReleased(evt);
            }
        });
        add(txtWeight);
        txtWeight.setBounds(760, 170, 130, 30);

        jLabel35.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("(Kg)");
        add(jLabel35);
        jLabel35.setBounds(890, 180, 22, 20);

        jLabel36.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("(cm)");
        add(jLabel36);
        jLabel36.setBounds(890, 140, 22, 20);

        cmbGender.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        cmbGender.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        add(cmbGender);
        cmbGender.setBounds(210, 480, 150, 30);

        lblSave.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblSave.setForeground(new java.awt.Color(255, 255, 255));
        lblSave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/save.png"))); // NOI18N
        lblSave.setText("Save");
        lblSave.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSaveMouseClicked(evt);
            }
        });
        add(lblSave);
        lblSave.setBounds(840, 370, 90, 40);

        lblSave1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblSave1.setForeground(new java.awt.Color(255, 255, 255));
        lblSave1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSave1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/cancel.png"))); // NOI18N
        lblSave1.setText("Cancel");
        lblSave1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblSave1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSave1MouseClicked(evt);
            }
        });
        add(lblSave1);
        lblSave1.setBounds(660, 370, 140, 40);

        txtAge.setBackground(new Color(0,0,0,0f));
        txtAge.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtAge.setForeground(new java.awt.Color(255, 255, 255));
        txtAge.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAge.setAutoscrolls(false);
        txtAge.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtAge.setCaretColor(new java.awt.Color(255, 255, 255));
        txtAge.setOpaque(false);
        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        txtAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAgeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAgeKeyReleased(evt);
            }
        });
        add(txtAge);
        txtAge.setBounds(210, 440, 70, 30);

        datePicRegDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        add(datePicRegDate);
        datePicRegDate.setBounds(760, 90, 180, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/Untitled-1.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 3));
        add(jLabel1);
        jLabel1.setBounds(0, 0, 970, 570);

        txtDOB1.setBackground(new Color(0,0,0,0f));
        txtDOB1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtDOB1.setForeground(new java.awt.Color(255, 255, 255));
        txtDOB1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDOB1.setAutoscrolls(false);
        txtDOB1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtDOB1.setCaretColor(new java.awt.Color(255, 255, 255));
        txtDOB1.setOpaque(false);
        txtDOB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDOB1ActionPerformed(evt);
            }
        });
        txtDOB1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDOB1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDOB1KeyReleased(evt);
            }
        });
        add(txtDOB1);
        txtDOB1.setBounds(210, 400, 230, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        if(Validation.validationEmail(txtEmail)){
            txtPhone.requestFocus();
        }else{
            JOptionPane.showMessageDialog(this,"Invalid Email");
        }
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyPressed
//        if (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE) {
//            Toolkit.getDefaultToolkit();
//            Validation.emailValidation(txtEmail);
//        }
    }//GEN-LAST:event_txtEmailKeyPressed

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailKeyReleased

    private void txtDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDOBActionPerformed
        if(Validation.dobValidation(txtDOB)){
            txtAge.requestFocus();
        }else{
            JOptionPane.showMessageDialog(this,"Invalid Date of Birth");
        }
    }//GEN-LAST:event_txtDOBActionPerformed

    private void txtDOBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDOBKeyPressed

    }//GEN-LAST:event_txtDOBKeyPressed

    private void txtDOBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDOBKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDOBKeyReleased

    private void txtMemberIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMemberIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMemberIDActionPerformed

    private void txtMemberIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMemberIDKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMemberIDKeyPressed

    private void txtMemberIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMemberIDKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMemberIDKeyReleased

    private void txtEmrContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmrContactActionPerformed
        if(Validation.phoneNumber(txtEmrContact)){
            lblSave.requestFocus();
        }else{
            JOptionPane.showMessageDialog(this,"Invalid Contact Number");
        }
    }//GEN-LAST:event_txtEmrContactActionPerformed

    private void txtEmrContactKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmrContactKeyPressed
        
    }//GEN-LAST:event_txtEmrContactKeyPressed

    private void txtEmrContactKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmrContactKeyReleased
        
    }//GEN-LAST:event_txtEmrContactKeyReleased

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
       if(Validation.phoneNumber(txtPhone)){
           txtEmrContact.requestFocus();
       }else{
           JOptionPane.showMessageDialog(this,"Invalid Phone Number");
       }
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void txtPhoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneKeyPressed
        
    }//GEN-LAST:event_txtPhoneKeyPressed

    private void txtPhoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneKeyReleased
       
    }//GEN-LAST:event_txtPhoneKeyReleased

    private void txtMemberRegNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMemberRegNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMemberRegNoActionPerformed

    private void txtMemberRegNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMemberRegNoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMemberRegNoKeyPressed

    private void txtMemberRegNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMemberRegNoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMemberRegNoKeyReleased

    private void lblMenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenMouseClicked
        ManageMemberHealthHistory healthHistory = new ManageMemberHealthHistory();
        JPanel middlePanel = HomePage.getMainPanel();
        middlePanel.removeAll();
        healthHistory.setSize(middlePanel.getSize());
        middlePanel.add(healthHistory);
        middlePanel.revalidate();
        middlePanel.repaint();
    }//GEN-LAST:event_lblMenMouseClicked

    private void txtHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHeightActionPerformed

    private void txtHeightKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHeightKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHeightKeyPressed

    private void txtHeightKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHeightKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHeightKeyReleased

    private void txtWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWeightActionPerformed

    private void txtWeightKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWeightKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWeightKeyPressed

    private void txtWeightKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWeightKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWeightKeyReleased

    private void lblSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaveMouseClicked
        
        try {
            MemeberDTO member = new MemeberDTO(
                    txtMemberID.getText(),
                    txtMemberName.getText(),
                    txtNIC.getText(),
                    txtOccupation.getText(),
                    txtAddress.getText(),
                    txtDOB.getText(),
                    Integer.parseInt(txtAge.getText()),
                    cmbGender.getSelectedItem().toString(),
                    Double.parseDouble(txtHeight.getText()),
                    Double.parseDouble(txtWeight.getText()),
                    txtEmail.getText(),
                    txtPhone.getText(),
                    txtEmrContact.getText()
            );
            Date date = datePicRegDate.getDate();
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String dateF = dateFormat.format(date);

            RegistrationDTO registration = new RegistrationDTO(
                    txtMemberRegNo.getText(),
                    dateF,
                    txtMemberID.getText()
            );

            boolean result = RegMemberController.addRegistration(registration, member);

            if (result) {
            
                JOptionPane.showMessageDialog(this, "Member has been successfully Saved.");
            } else {
                JOptionPane.showMessageDialog(this, "Member hasn't been Saved due to some error");
            }
        } catch (Exception ex) {
            Logger.getLogger(RegMemberPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
       // clearAllTextFileds();
        txtMemberRegNo.requestFocus();
        
    }//GEN-LAST:event_lblSaveMouseClicked

    private void lblSave1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSave1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSave1MouseClicked

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtAgeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyPressed
        
    }//GEN-LAST:event_txtAgeKeyPressed

    private void txtAgeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeKeyReleased

    private void txtDOB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDOB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDOB1ActionPerformed

    private void txtDOB1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDOB1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDOB1KeyPressed

    private void txtDOB1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDOB1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDOB1KeyReleased

    private void txtMemberNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMemberNameKeyPressed
       
    }//GEN-LAST:event_txtMemberNameKeyPressed

    private void txtNICKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNICKeyPressed
//        if (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE) {
//            Toolkit.getDefaultToolkit();
//            Validation.nicValidation(txtNIC);
//        }
    }//GEN-LAST:event_txtNICKeyPressed

    private void txtNICKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNICKeyReleased
//        if (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE) {
//            Toolkit.getDefaultToolkit();
//            Validation.nicValidation(txtNIC);
//        }
    }//GEN-LAST:event_txtNICKeyReleased

    private void txtMemberNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMemberNameKeyReleased
        
    }//GEN-LAST:event_txtMemberNameKeyReleased

    private void txtMemberNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMemberNameActionPerformed
        if(Validation.name(txtMemberName)){
            txtNIC.requestFocus();
        }else{
            JOptionPane.showMessageDialog(this,"Invalid Name");
                    
        }
    }//GEN-LAST:event_txtMemberNameActionPerformed

    private void txtNICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNICActionPerformed
        if(Validation.nicValidation(txtNIC)){
            txtOccupation.requestFocus();
        }else{
            JOptionPane.showMessageDialog(this,"Invalid NIC");
        }
    }//GEN-LAST:event_txtNICActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbGender;
    private org.jdesktop.swingx.JXDatePicker datePicRegDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblMen;
    private javax.swing.JLabel lblSave;
    private javax.swing.JLabel lblSave1;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtDOB1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmrContact;
    private javax.swing.JTextField txtHeight;
    private static javax.swing.JTextField txtMemberID;
    private javax.swing.JTextField txtMemberName;
    private javax.swing.JTextField txtMemberRegNo;
    private javax.swing.JTextField txtNIC;
    private javax.swing.JTextField txtOccupation;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables

    /*private void clearAllTextFileds() {
        txtMemberRegNo.setText("");
        txtMemberID.setText("");
        datePicRegDate.setDate(null);
        txtMemberName.setText("");
        txtNIC.setText("");
        txtOccupation.setText("");
        txtAddress.setText("");
        txtDOB.setText("");
        txtAge.setText("");
        cmbGender.setSelectedItem(null);
        txtHeight.setText("");
        txtWeight.setText("");
        txtEmail.setText("");
        txtPhone.setText("");
        txtEmrContact.setText("");
    }*/
    public static String getMemberID(){
        String memeberID=txtMemberID.getText();
        return memeberID;
    }
   
    private void getRegistrationID() {
        String newID;
        try {
            newID = IDGenarator.getNewID("registration","Member_RegNo", "Mreg");
            txtMemberRegNo.setText(newID);

        } catch (SQLException ex) {
            Logger.getLogger(RegMemberPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegMemberPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void getMemID() {
        String newID;
        try {
            newID = IDGenarator.getNewID("member","Member_ID", "Mem");
            txtMemberID.setText(newID);

        } catch (SQLException ex) {
            Logger.getLogger(RegMemberPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegMemberPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
