/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.mygymmanagement.view.panel;

import java.awt.Color;
import java.sql.Connection;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;
import lk.ijse.jasper.IJSEJasperViewer;
import lk.ijse.jasper.JasperUtil;
import lk.ijse.jasper.Report;
import lk.ijse.mygymmanagementsystem.dao.db.DBConnection;
import lk.ijse.mygymmanagementsystem.view.HomePage;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.JasperReportsContext;

/**
 *
 * @author Chinthaka
 */
@Report("lk.ijse.mygymmanagement.report")
public class ReportForPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public ReportForPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lblMemberDetails = new javax.swing.JLabel();
        lblMemberDetailsPic = new javax.swing.JLabel();
        lblPayment = new javax.swing.JLabel();
        lblPaymentPic = new javax.swing.JLabel();
        lblGrowth = new javax.swing.JLabel();
        lblgrowthPic = new javax.swing.JLabel();
        lblInventoryDetails = new javax.swing.JLabel();
        lblInventoryPic = new javax.swing.JLabel();
        lblAttendence = new javax.swing.JLabel();
        lblAttendencePic = new javax.swing.JLabel();
        lblmain = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(970, 570));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Stencil Std", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/setting-2.png"))); // NOI18N
        jLabel2.setText("report..");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 190, 50);

        lblMemberDetails.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblMemberDetails.setForeground(new java.awt.Color(255, 255, 255));
        lblMemberDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMemberDetails.setText("Member Details");
        lblMemberDetails.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblMemberDetails.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        lblMemberDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMemberDetailsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMemberDetailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMemberDetailsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMemberDetailsMousePressed(evt);
            }
        });
        add(lblMemberDetails);
        lblMemberDetails.setBounds(70, 100, 200, 200);

        lblMemberDetailsPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/memberDetails.png"))); // NOI18N
        add(lblMemberDetailsPic);
        lblMemberDetailsPic.setBounds(90, 110, 165, 165);

        lblPayment.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblPayment.setForeground(new java.awt.Color(255, 255, 255));
        lblPayment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPayment.setText("Payment");
        lblPayment.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblPayment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        lblPayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPaymentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPaymentMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPaymentMouseClicked(evt);
            }
        });
        add(lblPayment);
        lblPayment.setBounds(360, 100, 200, 200);

        lblPaymentPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/payement.png"))); // NOI18N
        add(lblPaymentPic);
        lblPaymentPic.setBounds(380, 100, 165, 165);

        lblGrowth.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblGrowth.setForeground(new java.awt.Color(255, 255, 255));
        lblGrowth.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGrowth.setText("Growth");
        lblGrowth.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblGrowth.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        lblGrowth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblGrowthMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblGrowthMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblGrowthMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGrowthMouseClicked(evt);
            }
        });
        add(lblGrowth);
        lblGrowth.setBounds(510, 340, 200, 200);

        lblgrowthPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/growth.png"))); // NOI18N
        add(lblgrowthPic);
        lblgrowthPic.setBounds(540, 350, 165, 165);

        lblInventoryDetails.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblInventoryDetails.setForeground(new java.awt.Color(255, 255, 255));
        lblInventoryDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInventoryDetails.setText("Inventory Details");
        lblInventoryDetails.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblInventoryDetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        lblInventoryDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblInventoryDetailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblInventoryDetailsMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInventoryDetailsMouseClicked(evt);
            }
        });
        add(lblInventoryDetails);
        lblInventoryDetails.setBounds(210, 340, 200, 200);

        lblInventoryPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/inventory.png"))); // NOI18N
        add(lblInventoryPic);
        lblInventoryPic.setBounds(230, 340, 165, 165);

        lblAttendence.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblAttendence.setForeground(new java.awt.Color(255, 255, 255));
        lblAttendence.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAttendence.setText("Attendence");
        lblAttendence.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblAttendence.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        lblAttendence.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAttendenceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAttendenceMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblAttendenceMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAttendenceMouseClicked(evt);
            }
        });
        add(lblAttendence);
        lblAttendence.setBounds(650, 100, 200, 200);

        lblAttendencePic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/attendence_1.png"))); // NOI18N
        add(lblAttendencePic);
        lblAttendencePic.setBounds(670, 100, 165, 165);

        lblmain.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(255, 153, 51), new java.awt.Color(255, 153, 51), new java.awt.Color(255, 153, 51), new java.awt.Color(255, 153, 51)));
        add(lblmain);
        lblmain.setBounds(20, 70, 910, 490);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/Untitled-1.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 3));
        add(jLabel1);
        jLabel1.setBounds(0, 0, 970, 570);
    }// </editor-fold>//GEN-END:initComponents

    private void lblMemberDetailsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMemberDetailsMousePressed
       
        
    }//GEN-LAST:event_lblMemberDetailsMousePressed

    private void lblGrowthMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGrowthMousePressed

    }//GEN-LAST:event_lblGrowthMousePressed

    private void lblMemberDetailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMemberDetailsMouseEntered
        lblMemberDetails.setBorder(new LineBorder(new Color(255, 153, 51), 3));
        lblMemberDetails.setForeground(new Color(255, 153, 51));

    }//GEN-LAST:event_lblMemberDetailsMouseEntered

    private void lblMemberDetailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMemberDetailsMouseExited
        lblMemberDetails.setBorder(new LineBorder(Color.WHITE, 3));
        lblMemberDetails.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblMemberDetailsMouseExited

    private void lblPaymentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPaymentMouseEntered
        lblPayment.setBorder(new LineBorder(new Color(255, 153, 51), 3));
        lblPayment.setForeground(new Color(255, 153, 51));
    }//GEN-LAST:event_lblPaymentMouseEntered

    private void lblPaymentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPaymentMouseExited
        lblPayment.setBorder(new LineBorder(Color.WHITE, 3));
        lblPayment.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblPaymentMouseExited

    private void lblInventoryDetailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInventoryDetailsMouseEntered
        lblInventoryDetails.setBorder(new LineBorder(new Color(255, 153, 51), 3));
        lblInventoryDetails.setForeground(new Color(255, 153, 51));
    }//GEN-LAST:event_lblInventoryDetailsMouseEntered

    private void lblInventoryDetailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInventoryDetailsMouseExited
        lblInventoryDetails.setBorder(new LineBorder(Color.WHITE, 3));
        lblInventoryDetails.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblInventoryDetailsMouseExited

    private void lblGrowthMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGrowthMouseEntered
        lblGrowth.setBorder(new LineBorder(new Color(255, 153, 51), 3));
        lblGrowth.setForeground(new Color(255, 153, 51));
    }//GEN-LAST:event_lblGrowthMouseEntered

    private void lblGrowthMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGrowthMouseExited
        lblGrowth.setBorder(new LineBorder(Color.WHITE, 3));
        lblGrowth.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblGrowthMouseExited

    private void lblMemberDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMemberDetailsMouseClicked
       try {
            JasperUtil.init(ReportForPanel.class);
            JasperReportsContext ctx = JasperUtil.getReportContext();
            JasperReport compiledReport=JasperUtil.getCompiledReport("member.jasper");
            JasperFillManager fillManager = JasperFillManager.getInstance(ctx);
            HashMap<String, Object> reportParams=new HashMap<>();
            Connection conn=DBConnection.getInstance().getConnection();
            JasperPrint filledReport = fillManager.fill(compiledReport, reportParams,conn);
            
            IJSEJasperViewer mjv=new IJSEJasperViewer(filledReport);
            mjv.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(ReportForPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        MemberDetailsReportPanel mdrp = new MemberDetailsReportPanel();
        JPanel middlePanel = HomePage.getMainPanel();
        middlePanel.removeAll();
        mdrp.setSize(middlePanel.getSize());
        middlePanel.add(mdrp);
        middlePanel.revalidate();
        middlePanel.repaint();
        
        
    }//GEN-LAST:event_lblMemberDetailsMouseClicked

    private void lblPaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPaymentMouseClicked
        PaymentReport pr = new PaymentReport();
        JPanel middlePanel = HomePage.getMainPanel();
        middlePanel.removeAll();
        pr.setSize(middlePanel.getSize());
        middlePanel.add(pr);
        middlePanel.revalidate();
        middlePanel.repaint();
    }//GEN-LAST:event_lblPaymentMouseClicked

    private void lblGrowthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGrowthMouseClicked
        GrowthReport gr = new GrowthReport();
        JPanel middlePanel = HomePage.getMainPanel();
        middlePanel.removeAll();
        gr.setSize(middlePanel.getSize());
        middlePanel.add(gr);
        middlePanel.revalidate();
        middlePanel.repaint();
    }//GEN-LAST:event_lblGrowthMouseClicked

    private void lblAttendenceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAttendenceMouseClicked
        AttendenceReport ar = new AttendenceReport();
        JPanel middlePanel = HomePage.getMainPanel();
        middlePanel.removeAll();
        ar.setSize(middlePanel.getSize());
        middlePanel.add(ar);
        middlePanel.revalidate();
        middlePanel.repaint();
    }//GEN-LAST:event_lblAttendenceMouseClicked

    private void lblAttendenceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAttendenceMouseEntered
        lblAttendence.setBorder(new LineBorder(new Color(255, 153, 51), 3));
        lblAttendence.setForeground(new Color(255, 153, 51));
    }//GEN-LAST:event_lblAttendenceMouseEntered

    private void lblAttendenceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAttendenceMouseExited
        lblAttendence.setBorder(new LineBorder(Color.WHITE, 3));
        lblAttendence.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblAttendenceMouseExited

    private void lblAttendenceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAttendenceMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAttendenceMousePressed

    private void lblInventoryDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInventoryDetailsMouseClicked
        InventoryReport ir = new InventoryReport();
        JPanel middlePanel = HomePage.getMainPanel();
        middlePanel.removeAll();
        ir.setSize(middlePanel.getSize());
        middlePanel.add(ir);
        middlePanel.revalidate();
        middlePanel.repaint();
    }//GEN-LAST:event_lblInventoryDetailsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAttendence;
    private javax.swing.JLabel lblAttendencePic;
    private javax.swing.JLabel lblGrowth;
    private javax.swing.JLabel lblInventoryDetails;
    private javax.swing.JLabel lblInventoryPic;
    private javax.swing.JLabel lblMemberDetails;
    private javax.swing.JLabel lblMemberDetailsPic;
    private javax.swing.JLabel lblPayment;
    private javax.swing.JLabel lblPaymentPic;
    private javax.swing.JLabel lblgrowthPic;
    private javax.swing.JLabel lblmain;
    // End of variables declaration//GEN-END:variables
}
