/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.mygymmanagement.view.panel;

import javax.swing.JPanel;
import java.awt.Color;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import lk.ijse.mygymmanagement.controller.ExerciseController;
import lk.ijse.mygymmanagement.controller.ManageInstructorController;
import lk.ijse.mygymmanagement.controller.MemberController;
import lk.ijse.mygymmanagement.controller.PaymentChargeController;
import lk.ijse.mygymmanagement.controller.RegMemberController;
import lk.ijse.mygymmanagement.controller.ScheduleController;
import lk.ijse.mygymmanagement.controller.ScheduleDetailController;
import lk.ijse.mygymmanagement.dao.DAOFactory;
import lk.ijse.mygymmanagement.dao.SuperDAO;
import lk.ijse.mygymmanagement.dao.custom.QueryDAO;
import lk.ijse.mygymmanagementsystem.commmon.IDGenarator;
import lk.ijse.mygymmanagementsystem.core.dto.ExerciseDTO;
import lk.ijse.mygymmanagementsystem.core.dto.InstructorDTO;
import lk.ijse.mygymmanagementsystem.core.dto.MemeberDTO;
import lk.ijse.mygymmanagementsystem.core.dto.PaymentChargeDTO;
import lk.ijse.mygymmanagementsystem.core.dto.RegistrationDTO;
import lk.ijse.mygymmanagementsystem.core.dto.ScheduleDTO;
import lk.ijse.mygymmanagementsystem.core.dto.ScheduleDetailDTO;
import lk.ijse.mygymmanagementsystem.core.dto.ScheduleInfoDTO;
import lk.ijse.mygymmanagementsystem.view.HomePage;

/**
 *
 * @author Chinthaka
 */
public class SchedulePanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public SchedulePanel() {
        initComponents();
        loadMemberRegNo();
        loadAllExerciseIDs();
        loadAllInstructors();
        getScheduleID();
        getScheduleDetailID();

        //loadAllScheduleDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtSet = new javax.swing.JTextField();
        lblMen = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        cmbMemberRegNo = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        txtMemberName = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtScheduledetailID = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtRep = new javax.swing.JTextField();
        txtInstructorName = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        txtScheduleID = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cmbInstructorID = new javax.swing.JComboBox<>();
        cmbExerciseID = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSchedule = new javax.swing.JTable();
        lblMen2 = new javax.swing.JLabel();
        lblView = new javax.swing.JLabel();
        lblPrint = new javax.swing.JLabel();
        txtEndDate = new javax.swing.JTextField();
        txtStartDate = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        txtExerciseName = new javax.swing.JTextField();
        lblSave = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(970, 570));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Stencil Std", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/schedule.png"))); // NOI18N
        jLabel2.setText("Schedule Information..");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 410, 50);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Set");
        add(jLabel13);
        jLabel13.setBounds(830, 70, 70, 20);

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText(":");
        add(jLabel24);
        jLabel24.setBounds(920, 70, 20, 20);

        txtSet.setBackground(new Color(0,0,0,0f));
        txtSet.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtSet.setForeground(new java.awt.Color(255, 255, 255));
        txtSet.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSet.setAutoscrolls(false);
        txtSet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtSet.setCaretColor(new java.awt.Color(255, 255, 255));
        txtSet.setOpaque(false);
        txtSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSetActionPerformed(evt);
            }
        });
        txtSet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSetKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSetKeyReleased(evt);
            }
        });
        add(txtSet);
        txtSet.setBounds(830, 90, 110, 26);

        lblMen.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblMen.setForeground(new java.awt.Color(255, 255, 255));
        lblMen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMen.setText("Modify Schedule");
        lblMen.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        lblMen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenMouseClicked(evt);
            }
        });
        add(lblMen);
        lblMen.setBounds(20, 380, 170, 30);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Member Reg.No");
        add(jLabel14);
        jLabel14.setBounds(30, 90, 140, 28);

        jLabel35.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText(":");
        add(jLabel35);
        jLabel35.setBounds(170, 90, 20, 28);

        cmbMemberRegNo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cmbMemberRegNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        cmbMemberRegNo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbMemberRegNoItemStateChanged(evt);
            }
        });
        add(cmbMemberRegNo);
        cmbMemberRegNo.setBounds(30, 130, 160, 30);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Member Name");
        add(jLabel15);
        jLabel15.setBounds(20, 190, 100, 20);

        txtMemberName.setBackground(new Color(0,0,0,0f));
        txtMemberName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtMemberName.setForeground(new java.awt.Color(255, 255, 255));
        txtMemberName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMemberName.setAutoscrolls(false);
        txtMemberName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtMemberName.setCaretColor(new java.awt.Color(255, 255, 255));
        txtMemberName.setOpaque(false);
        txtMemberName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMemberNameActionPerformed(evt);
            }
        });
        txtMemberName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMemberNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMemberNameKeyReleased(evt);
            }
        });
        add(txtMemberName);
        txtMemberName.setBounds(20, 210, 180, 30);

        jLabel36.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText(":");
        add(jLabel36);
        jLabel36.setBounds(160, 190, 20, 20);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Start Date");
        add(jLabel17);
        jLabel17.setBounds(530, 70, 120, 20);

        jLabel37.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText(":");
        add(jLabel37);
        jLabel37.setBounds(650, 70, 20, 20);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Instructor ID");
        add(jLabel18);
        jLabel18.setBounds(680, 70, 120, 20);

        jLabel38.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText(":");
        add(jLabel38);
        jLabel38.setBounds(800, 70, 20, 20);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Schedule Detail ID");
        add(jLabel19);
        jLabel19.setBounds(230, 120, 120, 20);

        txtScheduledetailID.setBackground(new Color(0,0,0,0f));
        txtScheduledetailID.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtScheduledetailID.setForeground(new java.awt.Color(255, 255, 255));
        txtScheduledetailID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtScheduledetailID.setAutoscrolls(false);
        txtScheduledetailID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtScheduledetailID.setCaretColor(new java.awt.Color(255, 255, 255));
        txtScheduledetailID.setOpaque(false);
        txtScheduledetailID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtScheduledetailIDActionPerformed(evt);
            }
        });
        txtScheduledetailID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtScheduledetailIDKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtScheduledetailIDKeyReleased(evt);
            }
        });
        add(txtScheduledetailID);
        txtScheduledetailID.setBounds(230, 140, 140, 30);

        jLabel39.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText(":");
        add(jLabel39);
        jLabel39.setBounds(350, 120, 20, 20);

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText(":");
        add(jLabel25);
        jLabel25.setBounds(920, 120, 20, 20);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Repetetion");
        add(jLabel16);
        jLabel16.setBounds(830, 120, 70, 20);

        txtRep.setBackground(new Color(0,0,0,0f));
        txtRep.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtRep.setForeground(new java.awt.Color(255, 255, 255));
        txtRep.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRep.setAutoscrolls(false);
        txtRep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtRep.setCaretColor(new java.awt.Color(255, 255, 255));
        txtRep.setOpaque(false);
        txtRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRepActionPerformed(evt);
            }
        });
        txtRep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRepKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRepKeyReleased(evt);
            }
        });
        add(txtRep);
        txtRep.setBounds(830, 140, 110, 30);

        txtInstructorName.setBackground(new Color(0,0,0,0f));
        txtInstructorName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtInstructorName.setForeground(new java.awt.Color(255, 255, 255));
        txtInstructorName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtInstructorName.setAutoscrolls(false);
        txtInstructorName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtInstructorName.setCaretColor(new java.awt.Color(255, 255, 255));
        txtInstructorName.setOpaque(false);
        txtInstructorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInstructorNameActionPerformed(evt);
            }
        });
        txtInstructorName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInstructorNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtInstructorNameKeyReleased(evt);
            }
        });
        add(txtInstructorName);
        txtInstructorName.setBounds(680, 140, 140, 30);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Instructor Name");
        add(jLabel20);
        jLabel20.setBounds(680, 120, 120, 20);

        jLabel40.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText(":");
        add(jLabel40);
        jLabel40.setBounds(800, 120, 20, 20);

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("End Date");
        add(jLabel21);
        jLabel21.setBounds(530, 120, 120, 20);

        jLabel41.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText(":");
        add(jLabel41);
        jLabel41.setBounds(650, 120, 20, 20);

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Exercise ID");
        add(jLabel22);
        jLabel22.setBounds(380, 70, 120, 20);

        jLabel42.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText(":");
        add(jLabel42);
        jLabel42.setBounds(500, 70, 20, 20);

        txtScheduleID.setBackground(new Color(0,0,0,0f));
        txtScheduleID.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtScheduleID.setForeground(new java.awt.Color(255, 255, 255));
        txtScheduleID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtScheduleID.setAutoscrolls(false);
        txtScheduleID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtScheduleID.setCaretColor(new java.awt.Color(255, 255, 255));
        txtScheduleID.setOpaque(false);
        txtScheduleID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtScheduleIDActionPerformed(evt);
            }
        });
        txtScheduleID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtScheduleIDKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtScheduleIDKeyReleased(evt);
            }
        });
        add(txtScheduleID);
        txtScheduleID.setBounds(230, 90, 140, 30);

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Schedule ID");
        add(jLabel23);
        jLabel23.setBounds(230, 70, 100, 20);

        jLabel43.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText(":");
        add(jLabel43);
        jLabel43.setBounds(350, 70, 20, 20);

        jLabel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search By", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        add(jLabel10);
        jLabel10.setBounds(10, 60, 190, 120);

        cmbInstructorID.setForeground(new java.awt.Color(255, 255, 255));
        cmbInstructorID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        cmbInstructorID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbInstructorIDItemStateChanged(evt);
            }
        });
        add(cmbInstructorID);
        cmbInstructorID.setBounds(680, 90, 140, 30);

        cmbExerciseID.setForeground(new java.awt.Color(255, 255, 255));
        cmbExerciseID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        cmbExerciseID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbExerciseIDItemStateChanged(evt);
            }
        });
        add(cmbExerciseID);
        cmbExerciseID.setBounds(380, 90, 140, 30);

        tblSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Schedule ID", "Exercise ID", "Exercise Name", "Start Date", "End Date", "Set", "Rep"
            }
        ));
        jScrollPane1.setViewportView(tblSchedule);

        add(jScrollPane1);
        jScrollPane1.setBounds(220, 190, 730, 250);

        lblMen2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblMen2.setForeground(new java.awt.Color(255, 255, 255));
        lblMen2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMen2.setText("Remove Schedule");
        lblMen2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        lblMen2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMen2MouseClicked(evt);
            }
        });
        add(lblMen2);
        lblMen2.setBounds(20, 430, 170, 30);

        lblView.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblView.setForeground(new java.awt.Color(255, 255, 255));
        lblView.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/save.png"))); // NOI18N
        lblView.setText("View");
        lblView.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        lblView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblViewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblViewMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblViewMouseClicked(evt);
            }
        });
        add(lblView);
        lblView.setBounds(60, 320, 100, 40);

        lblPrint.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblPrint.setForeground(new java.awt.Color(255, 255, 255));
        lblPrint.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrint.setText("Print Schedule");
        lblPrint.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        lblPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPrintMouseClicked(evt);
            }
        });
        add(lblPrint);
        lblPrint.setBounds(640, 500, 180, 40);

        txtEndDate.setBackground(new Color(0,0,0,0f));
        txtEndDate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtEndDate.setForeground(new java.awt.Color(255, 255, 255));
        txtEndDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEndDate.setAutoscrolls(false);
        txtEndDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtEndDate.setCaretColor(new java.awt.Color(255, 255, 255));
        txtEndDate.setOpaque(false);
        txtEndDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEndDateActionPerformed(evt);
            }
        });
        txtEndDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEndDateKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEndDateKeyReleased(evt);
            }
        });
        add(txtEndDate);
        txtEndDate.setBounds(530, 140, 140, 30);

        txtStartDate.setBackground(new Color(0,0,0,0f));
        txtStartDate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtStartDate.setForeground(new java.awt.Color(255, 255, 255));
        txtStartDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtStartDate.setAutoscrolls(false);
        txtStartDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtStartDate.setCaretColor(new java.awt.Color(255, 255, 255));
        txtStartDate.setOpaque(false);
        txtStartDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStartDateActionPerformed(evt);
            }
        });
        txtStartDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtStartDateKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtStartDateKeyReleased(evt);
            }
        });
        add(txtStartDate);
        txtStartDate.setBounds(530, 90, 140, 30);

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Exercise Name");
        add(jLabel26);
        jLabel26.setBounds(380, 120, 120, 20);

        jLabel44.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText(":");
        add(jLabel44);
        jLabel44.setBounds(500, 120, 20, 20);

        txtExerciseName.setBackground(new Color(0,0,0,0f));
        txtExerciseName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtExerciseName.setForeground(new java.awt.Color(255, 255, 255));
        txtExerciseName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtExerciseName.setAutoscrolls(false);
        txtExerciseName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtExerciseName.setCaretColor(new java.awt.Color(255, 255, 255));
        txtExerciseName.setOpaque(false);
        txtExerciseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExerciseNameActionPerformed(evt);
            }
        });
        txtExerciseName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtExerciseNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtExerciseNameKeyReleased(evt);
            }
        });
        add(txtExerciseName);
        txtExerciseName.setBounds(380, 140, 140, 30);

        lblSave.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblSave.setForeground(new java.awt.Color(255, 255, 255));
        lblSave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/save.png"))); // NOI18N
        lblSave.setText("Save");
        lblSave.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        lblSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSaveMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSaveMouseClicked(evt);
            }
        });
        add(lblSave);
        lblSave.setBounds(850, 500, 100, 40);

        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Schedule Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(210, 40, 750, 430);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/Untitled-1.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 3));
        add(jLabel1);
        jLabel1.setBounds(0, 0, 970, 570);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSetActionPerformed

    private void txtSetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSetKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSetKeyPressed

    private void txtSetKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSetKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSetKeyReleased

    private void lblMenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenMouseClicked

    }//GEN-LAST:event_lblMenMouseClicked

    private void txtMemberNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMemberNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMemberNameActionPerformed

    private void txtMemberNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMemberNameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMemberNameKeyPressed

    private void txtMemberNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMemberNameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMemberNameKeyReleased

    private void txtScheduledetailIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtScheduledetailIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtScheduledetailIDActionPerformed

    private void txtScheduledetailIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtScheduledetailIDKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtScheduledetailIDKeyPressed

    private void txtScheduledetailIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtScheduledetailIDKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtScheduledetailIDKeyReleased

    private void txtRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRepActionPerformed

    private void txtRepKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRepKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRepKeyPressed

    private void txtRepKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRepKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRepKeyReleased

    private void txtInstructorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInstructorNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInstructorNameActionPerformed

    private void txtInstructorNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInstructorNameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInstructorNameKeyPressed

    private void txtInstructorNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInstructorNameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInstructorNameKeyReleased

    private void txtScheduleIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtScheduleIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtScheduleIDActionPerformed

    private void txtScheduleIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtScheduleIDKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtScheduleIDKeyPressed

    private void txtScheduleIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtScheduleIDKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtScheduleIDKeyReleased

    private void lblViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewMouseClicked

        QueryDAO queryDAO = (QueryDAO) DAOFactory.getInstance().getDAO(DAOFactory.DAOTypes.QUERY);

        try {
            ArrayList<ScheduleInfoDTO> scheduleInfo = queryDAO.getScheduleInfo(cmbMemberRegNo.getSelectedItem().toString());

            DefaultTableModel dtm = (DefaultTableModel) tblSchedule.getModel();

            dtm.setRowCount(0);

            if (scheduleInfo != null) {

                for (ScheduleInfoDTO schedule : scheduleInfo) {

                    Object[] rowData = {
                        schedule.getScheduleID(),
                        schedule.getExerciseID(),
                        schedule.getExerciseName(),
                        schedule.getStartDate(),
                        schedule.getEndDate(),
                        schedule.getSets(),
                        schedule.getRep()
                    };

                    dtm.addRow(rowData);

                }

            }

        } catch (Exception ex) {
            Logger.getLogger(SchedulePanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_lblViewMouseClicked

    private void lblMen2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMen2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblMen2MouseClicked

    private void lblPrintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPrintMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblPrintMouseClicked

    private void cmbMemberRegNoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbMemberRegNoItemStateChanged
        try {
            RegistrationDTO registrationDTO = RegMemberController.searchRegistration((String) cmbMemberRegNo.getSelectedItem());
        } catch (Exception ex) {
            Logger.getLogger(PaymentPanel.class.getName()).log(Level.SEVERE, null, ex);

        }
        searchMember();
    }//GEN-LAST:event_cmbMemberRegNoItemStateChanged

    private void cmbExerciseIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbExerciseIDItemStateChanged
        try {
            ExerciseDTO exerciseDTO = ExerciseController.searchexercise((String) cmbExerciseID.getSelectedItem());
        } catch (Exception ex) {
            Logger.getLogger(PaymentPanel.class.getName()).log(Level.SEVERE, null, ex);

        }
        searchExercises();
    }//GEN-LAST:event_cmbExerciseIDItemStateChanged

    private void cmbInstructorIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbInstructorIDItemStateChanged
        try {
            InstructorDTO instructorDTO = ManageInstructorController.searchInstructor((String) cmbInstructorID.getSelectedItem());
        } catch (Exception ex) {
            Logger.getLogger(PaymentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        searchInstructor();
    }//GEN-LAST:event_cmbInstructorIDItemStateChanged

    private void txtEndDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEndDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEndDateActionPerformed

    private void txtEndDateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEndDateKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEndDateKeyPressed

    private void txtEndDateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEndDateKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEndDateKeyReleased

    private void txtStartDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStartDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStartDateActionPerformed

    private void txtStartDateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStartDateKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStartDateKeyPressed

    private void txtStartDateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStartDateKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStartDateKeyReleased

    private void txtExerciseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExerciseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExerciseNameActionPerformed

    private void txtExerciseNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtExerciseNameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExerciseNameKeyPressed

    private void txtExerciseNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtExerciseNameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExerciseNameKeyReleased

    private void lblViewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewMouseEntered
        lblView.setSize(110, 50);
    }//GEN-LAST:event_lblViewMouseEntered

    private void lblViewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewMouseExited
        lblView.setSize(100, 40);
    }//GEN-LAST:event_lblViewMouseExited

    private void lblSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaveMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSaveMouseEntered

    private void lblSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaveMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSaveMouseExited

    private void lblSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaveMouseClicked
        try {
            ScheduleDTO schedule = new ScheduleDTO(
                    txtScheduleID.getText(),
                    cmbMemberRegNo.getSelectedItem().toString(),
                    cmbInstructorID.getSelectedItem().toString(),
                    txtStartDate.getText(),
                    txtEndDate.getText()
            );

            ScheduleDetailDTO sDetail = new ScheduleDetailDTO(
                    txtScheduledetailID.getText(),
                    txtScheduleID.getText(),
                    cmbExerciseID.getSelectedItem().toString(),
                    txtSet.getText(),
                    txtRep.getText()
            );

            boolean result = ScheduleDetailController.addScheduleDetail(sDetail, schedule);

            if (result) {
                JOptionPane.showMessageDialog(this, "Schedule has been successfully Created.");
                clearTextFields();
                getScheduleDetailID();
                // getScheduleID();
            } else {
                JOptionPane.showMessageDialog(this, "Schedule hasn't been Created due to some error");
            }
        } catch (Exception ex) {
            Logger.getLogger(RegMemberPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        cmbMemberRegNo.requestFocus();

    }//GEN-LAST:event_lblSaveMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbExerciseID;
    private javax.swing.JComboBox<String> cmbInstructorID;
    private javax.swing.JComboBox<String> cmbMemberRegNo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMen;
    private javax.swing.JLabel lblMen2;
    private javax.swing.JLabel lblPrint;
    private javax.swing.JLabel lblSave;
    private javax.swing.JLabel lblView;
    private javax.swing.JTable tblSchedule;
    private javax.swing.JTextField txtEndDate;
    private javax.swing.JTextField txtExerciseName;
    private javax.swing.JTextField txtInstructorName;
    private javax.swing.JTextField txtMemberName;
    private javax.swing.JTextField txtRep;
    private javax.swing.JTextField txtScheduleID;
    private javax.swing.JTextField txtScheduledetailID;
    private javax.swing.JTextField txtSet;
    private javax.swing.JTextField txtStartDate;
    // End of variables declaration//GEN-END:variables

    private void loadMemberRegNo() {
        try {
            ArrayList<RegistrationDTO> RList = RegMemberController.getAllRegistration();
            if (RList == null) {
                return;
            }
            for (RegistrationDTO registrationDTO : RList) {
                cmbMemberRegNo.addItem(registrationDTO.getMemberRegNo());
            }
        } catch (Exception ex) {
            Logger.getLogger(PaymentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void searchMember() {
        String regisID = (String) cmbMemberRegNo.getSelectedItem();
        try {
            RegistrationDTO registrationDTO = RegMemberController.searchRegistration(regisID);
            if (registrationDTO != null) {
                String memberID = registrationDTO.getMemberID();
                MemeberDTO dTO = MemberController.searchMember(memberID);
                if (dTO != null) {
                    txtMemberName.setText(dTO.getMemberName());
                }
            } else {
                JOptionPane.showMessageDialog(this, "There is no Member for this registration ID.....");
            }
        } catch (Exception ex) {
            Logger.getLogger(PaymentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadAllExerciseIDs() {
        try {
            ArrayList<ExerciseDTO> exercise = ExerciseController.getAllExercise();
            if (exercise != null) {
                for (ExerciseDTO exerciseDTO : exercise) {
                    cmbExerciseID.addItem(exerciseDTO.getExerciseID());
                }
            }

        } catch (Exception ex) {
            Logger.getLogger(PaymentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadAllInstructors() {
        try {
            ArrayList<InstructorDTO> IList = ManageInstructorController.getAllInstructor();
            if (IList != null) {
                for (InstructorDTO instructorDTO : IList) {
                    cmbInstructorID.addItem(instructorDTO.getInstructorID());
                }
            }

        } catch (Exception ex) {
            Logger.getLogger(PaymentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void searchInstructor() {
        String IID = cmbInstructorID.getSelectedItem().toString();
        try {
            InstructorDTO instructorDTO = ManageInstructorController.searchInstructor(IID);
            if (instructorDTO != null) {
                txtInstructorName.setText(instructorDTO.getInstructorName());
            }
        } catch (Exception ex) {
            Logger.getLogger(PaymentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

//    private void loadAllScheduleDetails() {
//        try {
//            ArrayList<ScheduleDetailDTO> allSchedules = ScheduleDetailController.getAllScheduleDetail();
//            
//            DefaultTableModel dtm = (DefaultTableModel) tblSchedule.getModel();
//            
//            dtm.setRowCount(0);
//            
//            if (allSchedules != null) {
//                
//                for (ScheduleDetailDTO detail : allSchedules) {
//                    
//                    Object[] rowData = {
//                        detail.getExerciseID(),
//                        detail.getSets(),
//                        detail.getRepetetion()
//                    };
//                    
//                    dtm.addRow(rowData);
//                    
//                }
//                
//            }
//            
//        } catch (Exception ex) {
//            Logger.getLogger(ManageInventoryPanel.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }
//    
//    private void loadAllSchedule() {
//        try {
//            ArrayList<ScheduleDTO> allSchedules = ScheduleController.getAllSchedule();
//            
//            DefaultTableModel dtm = (DefaultTableModel) tblSchedule.getModel();
//            
//            dtm.setRowCount(0);
//            
//            if (allSchedules != null) {
//                
//                for (ScheduleDTO detail : allSchedules) {
//                    
//                    Object[] rowData = {
//                        detail.getScheduleID(),
//                        detail.getStartDate(),
//                        detail.getEndDate(),
//                    };
//                    
//                    dtm.addRow(rowData);
//                    
//                }
//                
//            }
//            
//        } catch (Exception ex) {
//            Logger.getLogger(ManageInventoryPanel.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }
    private void searchExercises() {
        String eID = cmbExerciseID.getSelectedItem().toString();
        try {
            ExerciseDTO exerciseDTO = ExerciseController.searchexercise(eID);
            if (exerciseDTO != null) {
                txtExerciseName.setText(exerciseDTO.getExerciseName());
            }
        } catch (Exception ex) {
            Logger.getLogger(PaymentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void getScheduleID() {
        String newID;
        try {
            newID = IDGenarator.getNewID("schedule", "Schedule_ID", "Sch");
            txtScheduleID.setText(newID);

        } catch (SQLException ex) {
            Logger.getLogger(RegMemberPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegMemberPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void getScheduleDetailID() {
        String newID;
        try {
            newID = IDGenarator.getNewID("scheduledetail", "Schedule_Detail_ID", "SchD");
            txtScheduledetailID.setText(newID);

        } catch (SQLException ex) {
            Logger.getLogger(RegMemberPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegMemberPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void clearTextFields() {
        //cmbExerciseID.setSelectedItem(null);
        txtExerciseName.setText("");
        txtStartDate.setText("");
        txtEndDate.setText("");
        //cmbInstructorID.setSelectedItem(null);
        txtInstructorName.setText("");
        txtSet.setText("");
        txtRep.setText("");
    }

}
