/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.mygymmanagement.view.panel;

import java.awt.Color;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import lk.ijse.mygymmanagement.controller.MeasurementController;
import lk.ijse.mygymmanagement.controller.MemberController;
import lk.ijse.mygymmanagement.controller.PaymentChargeController;
import lk.ijse.mygymmanagement.controller.RegMemberController;
import lk.ijse.mygymmanagementsystem.core.dto.MeasurementDTO;
import lk.ijse.mygymmanagementsystem.core.dto.MemeberDTO;
import lk.ijse.mygymmanagementsystem.core.dto.PaymentChargeDTO;
import lk.ijse.mygymmanagementsystem.core.dto.RegistrationDTO;
import lk.ijse.mygymmanagementsystem.view.HomePage;

/**
 *
 * @author Chinthaka
 */
public class ViewMeasurmentPanel1 extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public ViewMeasurmentPanel1() {
        initComponents();
        loadAllMemberID();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel21 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        cmbMemberID = new javax.swing.JComboBox<>();
        txtMemberName = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtNeck = new javax.swing.JTextField();
        txtShoulder = new javax.swing.JTextField();
        txtChest = new javax.swing.JTextField();
        txtWaist = new javax.swing.JTextField();
        txtHips = new javax.swing.JTextField();
        txtUpperL = new javax.swing.JTextField();
        txtForeL = new javax.swing.JTextField();
        txtThighL = new javax.swing.JTextField();
        txtCalfL = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtUpperR = new javax.swing.JTextField();
        txtForeR = new javax.swing.JTextField();
        txtThighR = new javax.swing.JTextField();
        txtCalfR = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(970, 570));
        setLayout(null);

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/back.png"))); // NOI18N
        jLabel21.setText("BACK");
        jLabel21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        add(jLabel21);
        jLabel21.setBounds(840, 10, 120, 50);

        jLabel2.setFont(new java.awt.Font("Stencil Std", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/measur.png"))); // NOI18N
        jLabel2.setText("Measurement View..");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 380, 50);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Member ID");
        add(jLabel14);
        jLabel14.setBounds(50, 100, 140, 30);

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText(":");
        add(jLabel29);
        jLabel29.setBounds(210, 100, 30, 30);

        cmbMemberID.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmbMemberID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        cmbMemberID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbMemberIDItemStateChanged(evt);
            }
        });
        add(cmbMemberID);
        cmbMemberID.setBounds(240, 100, 110, 30);

        txtMemberName.setBackground(new Color(0,0,0,0f));
        txtMemberName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtMemberName.setForeground(new java.awt.Color(255, 255, 255));
        txtMemberName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMemberName.setAutoscrolls(false);
        txtMemberName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtMemberName.setCaretColor(new java.awt.Color(255, 255, 255));
        txtMemberName.setOpaque(false);
        txtMemberName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMemberNameActionPerformed(evt);
            }
        });
        txtMemberName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMemberNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMemberNameKeyReleased(evt);
            }
        });
        add(txtMemberName);
        txtMemberName.setBounds(700, 100, 210, 30);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Member Name");
        add(jLabel15);
        jLabel15.setBounds(520, 100, 120, 30);

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText(":");
        add(jLabel30);
        jLabel30.setBounds(650, 100, 30, 30);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Neck");
        add(jLabel13);
        jLabel13.setBounds(60, 180, 100, 30);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Shoulders");
        add(jLabel16);
        jLabel16.setBounds(60, 220, 100, 30);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Chest");
        add(jLabel17);
        jLabel17.setBounds(60, 260, 100, 30);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Waist");
        add(jLabel18);
        jLabel18.setBounds(60, 300, 100, 30);

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Hips");
        add(jLabel25);
        jLabel25.setBounds(60, 340, 100, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Upper Arm");
        add(jLabel8);
        jLabel8.setBounds(60, 380, 120, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Forearm");
        add(jLabel6);
        jLabel6.setBounds(60, 420, 100, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Thigh");
        add(jLabel9);
        jLabel9.setBounds(60, 460, 100, 30);

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Calf");
        add(jLabel26);
        jLabel26.setBounds(60, 500, 100, 30);

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText(":");
        add(jLabel32);
        jLabel32.setBounds(180, 500, 20, 30);

        jLabel33.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText(":");
        add(jLabel33);
        jLabel33.setBounds(180, 460, 20, 30);

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText(":");
        add(jLabel28);
        jLabel28.setBounds(180, 420, 20, 30);

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText(":");
        add(jLabel23);
        jLabel23.setBounds(180, 380, 20, 30);

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText(":");
        add(jLabel22);
        jLabel22.setBounds(180, 340, 20, 30);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText(":");
        add(jLabel20);
        jLabel20.setBounds(180, 300, 20, 30);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText(":");
        add(jLabel19);
        jLabel19.setBounds(180, 260, 20, 30);

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText(":");
        add(jLabel24);
        jLabel24.setBounds(180, 220, 20, 30);

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText(":");
        add(jLabel27);
        jLabel27.setBounds(180, 180, 20, 30);

        txtNeck.setBackground(new Color(0,0,0,0f));
        txtNeck.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtNeck.setForeground(new java.awt.Color(255, 255, 255));
        txtNeck.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNeck.setAutoscrolls(false);
        txtNeck.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtNeck.setCaretColor(new java.awt.Color(255, 255, 255));
        txtNeck.setOpaque(false);
        txtNeck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNeckActionPerformed(evt);
            }
        });
        txtNeck.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNeckKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNeckKeyReleased(evt);
            }
        });
        add(txtNeck);
        txtNeck.setBounds(220, 180, 110, 30);

        txtShoulder.setBackground(new Color(0,0,0,0f));
        txtShoulder.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtShoulder.setForeground(new java.awt.Color(255, 255, 255));
        txtShoulder.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtShoulder.setAutoscrolls(false);
        txtShoulder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtShoulder.setCaretColor(new java.awt.Color(255, 255, 255));
        txtShoulder.setOpaque(false);
        txtShoulder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtShoulderActionPerformed(evt);
            }
        });
        txtShoulder.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtShoulderKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtShoulderKeyReleased(evt);
            }
        });
        add(txtShoulder);
        txtShoulder.setBounds(220, 220, 110, 30);

        txtChest.setBackground(new Color(0,0,0,0f));
        txtChest.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtChest.setForeground(new java.awt.Color(255, 255, 255));
        txtChest.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtChest.setAutoscrolls(false);
        txtChest.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtChest.setCaretColor(new java.awt.Color(255, 255, 255));
        txtChest.setOpaque(false);
        txtChest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChestActionPerformed(evt);
            }
        });
        txtChest.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtChestKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtChestKeyReleased(evt);
            }
        });
        add(txtChest);
        txtChest.setBounds(220, 260, 110, 30);

        txtWaist.setBackground(new Color(0,0,0,0f));
        txtWaist.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtWaist.setForeground(new java.awt.Color(255, 255, 255));
        txtWaist.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtWaist.setAutoscrolls(false);
        txtWaist.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtWaist.setCaretColor(new java.awt.Color(255, 255, 255));
        txtWaist.setOpaque(false);
        txtWaist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWaistActionPerformed(evt);
            }
        });
        txtWaist.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtWaistKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtWaistKeyReleased(evt);
            }
        });
        add(txtWaist);
        txtWaist.setBounds(220, 300, 110, 30);

        txtHips.setBackground(new Color(0,0,0,0f));
        txtHips.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtHips.setForeground(new java.awt.Color(255, 255, 255));
        txtHips.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHips.setAutoscrolls(false);
        txtHips.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtHips.setCaretColor(new java.awt.Color(255, 255, 255));
        txtHips.setOpaque(false);
        txtHips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHipsActionPerformed(evt);
            }
        });
        txtHips.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHipsKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHipsKeyReleased(evt);
            }
        });
        add(txtHips);
        txtHips.setBounds(220, 340, 110, 30);

        txtUpperL.setBackground(new Color(0,0,0,0f));
        txtUpperL.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtUpperL.setForeground(new java.awt.Color(255, 255, 255));
        txtUpperL.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUpperL.setAutoscrolls(false);
        txtUpperL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtUpperL.setCaretColor(new java.awt.Color(255, 255, 255));
        txtUpperL.setOpaque(false);
        txtUpperL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpperLActionPerformed(evt);
            }
        });
        txtUpperL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUpperLKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUpperLKeyReleased(evt);
            }
        });
        add(txtUpperL);
        txtUpperL.setBounds(220, 380, 110, 30);

        txtForeL.setBackground(new Color(0,0,0,0f));
        txtForeL.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtForeL.setForeground(new java.awt.Color(255, 255, 255));
        txtForeL.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtForeL.setAutoscrolls(false);
        txtForeL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtForeL.setCaretColor(new java.awt.Color(255, 255, 255));
        txtForeL.setOpaque(false);
        txtForeL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtForeLActionPerformed(evt);
            }
        });
        txtForeL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtForeLKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtForeLKeyReleased(evt);
            }
        });
        add(txtForeL);
        txtForeL.setBounds(220, 420, 110, 30);

        txtThighL.setBackground(new Color(0,0,0,0f));
        txtThighL.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtThighL.setForeground(new java.awt.Color(255, 255, 255));
        txtThighL.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtThighL.setAutoscrolls(false);
        txtThighL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtThighL.setCaretColor(new java.awt.Color(255, 255, 255));
        txtThighL.setOpaque(false);
        txtThighL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThighLActionPerformed(evt);
            }
        });
        txtThighL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtThighLKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtThighLKeyReleased(evt);
            }
        });
        add(txtThighL);
        txtThighL.setBounds(220, 460, 110, 30);

        txtCalfL.setBackground(new Color(0,0,0,0f));
        txtCalfL.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtCalfL.setForeground(new java.awt.Color(255, 255, 255));
        txtCalfL.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCalfL.setAutoscrolls(false);
        txtCalfL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtCalfL.setCaretColor(new java.awt.Color(255, 255, 255));
        txtCalfL.setOpaque(false);
        txtCalfL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCalfLActionPerformed(evt);
            }
        });
        txtCalfL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCalfLKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCalfLKeyReleased(evt);
            }
        });
        add(txtCalfL);
        txtCalfL.setBounds(220, 500, 110, 30);

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("(L)");
        add(jLabel48);
        jLabel48.setBounds(340, 500, 20, 30);

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("(L)");
        add(jLabel44);
        jLabel44.setBounds(340, 460, 20, 30);

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("(L)");
        add(jLabel40);
        jLabel40.setBounds(340, 420, 20, 30);

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("(L)");
        add(jLabel34);
        jLabel34.setBounds(340, 380, 20, 20);

        txtUpperR.setBackground(new Color(0,0,0,0f));
        txtUpperR.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtUpperR.setForeground(new java.awt.Color(255, 255, 255));
        txtUpperR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUpperR.setAutoscrolls(false);
        txtUpperR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtUpperR.setCaretColor(new java.awt.Color(255, 255, 255));
        txtUpperR.setOpaque(false);
        txtUpperR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpperRActionPerformed(evt);
            }
        });
        txtUpperR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUpperRKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUpperRKeyReleased(evt);
            }
        });
        add(txtUpperR);
        txtUpperR.setBounds(370, 380, 110, 30);

        txtForeR.setBackground(new Color(0,0,0,0f));
        txtForeR.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtForeR.setForeground(new java.awt.Color(255, 255, 255));
        txtForeR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtForeR.setAutoscrolls(false);
        txtForeR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtForeR.setCaretColor(new java.awt.Color(255, 255, 255));
        txtForeR.setOpaque(false);
        txtForeR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtForeRActionPerformed(evt);
            }
        });
        txtForeR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtForeRKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtForeRKeyReleased(evt);
            }
        });
        add(txtForeR);
        txtForeR.setBounds(370, 420, 110, 30);

        txtThighR.setBackground(new Color(0,0,0,0f));
        txtThighR.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtThighR.setForeground(new java.awt.Color(255, 255, 255));
        txtThighR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtThighR.setAutoscrolls(false);
        txtThighR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtThighR.setCaretColor(new java.awt.Color(255, 255, 255));
        txtThighR.setOpaque(false);
        txtThighR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThighRActionPerformed(evt);
            }
        });
        txtThighR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtThighRKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtThighRKeyReleased(evt);
            }
        });
        add(txtThighR);
        txtThighR.setBounds(370, 460, 110, 30);

        txtCalfR.setBackground(new Color(0,0,0,0f));
        txtCalfR.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtCalfR.setForeground(new java.awt.Color(255, 255, 255));
        txtCalfR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCalfR.setAutoscrolls(false);
        txtCalfR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        txtCalfR.setCaretColor(new java.awt.Color(255, 255, 255));
        txtCalfR.setOpaque(false);
        txtCalfR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCalfRActionPerformed(evt);
            }
        });
        txtCalfR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCalfRKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCalfRKeyReleased(evt);
            }
        });
        add(txtCalfR);
        txtCalfR.setBounds(370, 500, 110, 30);

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("(R)");
        add(jLabel49);
        jLabel49.setBounds(490, 500, 19, 30);

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("(R)");
        add(jLabel45);
        jLabel45.setBounds(490, 460, 19, 30);

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("(R)");
        add(jLabel41);
        jLabel41.setBounds(490, 420, 19, 30);

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("(R)");
        add(jLabel35);
        jLabel35.setBounds(490, 380, 19, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("inch");
        add(jLabel12);
        jLabel12.setBounds(260, 160, 30, 20);

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Measurement", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(255, 255, 255)))); // NOI18N
        add(jLabel31);
        jLabel31.setBounds(50, 140, 470, 410);

        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(255, 153, 51), new java.awt.Color(255, 153, 51), new java.awt.Color(255, 153, 51), new java.awt.Color(255, 153, 51)));
        add(jLabel3);
        jLabel3.setBounds(20, 70, 910, 490);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/Untitled-1.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 3));
        add(jLabel1);
        jLabel1.setBounds(0, 0, 970, 570);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        MesurementPanel mesurementPanel = new MesurementPanel();
        JPanel middlePanel = HomePage.getMainPanel();
        middlePanel.removeAll();
        mesurementPanel.setSize(middlePanel.getSize());
        middlePanel.add(mesurementPanel);
        middlePanel.revalidate();
        middlePanel.repaint();
    }//GEN-LAST:event_jLabel21MouseClicked

    private void cmbMemberIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbMemberIDItemStateChanged
        try {
            MemeberDTO memeberDTO=MemberController.searchMember((String) cmbMemberID.getSelectedItem());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        searchMember();
    }//GEN-LAST:event_cmbMemberIDItemStateChanged

    private void txtMemberNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMemberNameActionPerformed
        cmbMemberID.requestFocus();
    }//GEN-LAST:event_txtMemberNameActionPerformed

    private void txtMemberNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMemberNameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMemberNameKeyPressed

    private void txtMemberNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMemberNameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMemberNameKeyReleased

    private void txtNeckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNeckActionPerformed
        txtShoulder.requestFocus();
    }//GEN-LAST:event_txtNeckActionPerformed

    private void txtNeckKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNeckKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNeckKeyPressed

    private void txtNeckKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNeckKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNeckKeyReleased

    private void txtShoulderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtShoulderActionPerformed
        txtChest.requestFocus();
    }//GEN-LAST:event_txtShoulderActionPerformed

    private void txtShoulderKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtShoulderKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtShoulderKeyPressed

    private void txtShoulderKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtShoulderKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtShoulderKeyReleased

    private void txtChestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChestActionPerformed
        txtWaist.requestFocus();
    }//GEN-LAST:event_txtChestActionPerformed

    private void txtChestKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChestKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChestKeyPressed

    private void txtChestKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChestKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChestKeyReleased

    private void txtWaistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWaistActionPerformed
        txtHips.requestFocus();
    }//GEN-LAST:event_txtWaistActionPerformed

    private void txtWaistKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWaistKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWaistKeyPressed

    private void txtWaistKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWaistKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWaistKeyReleased

    private void txtHipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHipsActionPerformed
        txtUpperL.requestFocus();
    }//GEN-LAST:event_txtHipsActionPerformed

    private void txtHipsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHipsKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHipsKeyPressed

    private void txtHipsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHipsKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHipsKeyReleased

    private void txtUpperLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpperLActionPerformed
        txtUpperR.requestFocus();
    }//GEN-LAST:event_txtUpperLActionPerformed

    private void txtUpperLKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUpperLKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpperLKeyPressed

    private void txtUpperLKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUpperLKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpperLKeyReleased

    private void txtForeLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtForeLActionPerformed
        txtForeR.requestFocus();
    }//GEN-LAST:event_txtForeLActionPerformed

    private void txtForeLKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtForeLKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtForeLKeyPressed

    private void txtForeLKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtForeLKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtForeLKeyReleased

    private void txtThighLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThighLActionPerformed
        txtThighR.requestFocus();
    }//GEN-LAST:event_txtThighLActionPerformed

    private void txtThighLKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtThighLKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThighLKeyPressed

    private void txtThighLKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtThighLKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThighLKeyReleased

    private void txtCalfLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCalfLActionPerformed
        txtCalfR.requestFocus();
    }//GEN-LAST:event_txtCalfLActionPerformed

    private void txtCalfLKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCalfLKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCalfLKeyPressed

    private void txtCalfLKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCalfLKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCalfLKeyReleased

    private void txtUpperRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpperRActionPerformed
        txtForeL.requestFocus();
    }//GEN-LAST:event_txtUpperRActionPerformed

    private void txtUpperRKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUpperRKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpperRKeyPressed

    private void txtUpperRKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUpperRKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpperRKeyReleased

    private void txtForeRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtForeRActionPerformed
        txtThighL.requestFocus();
    }//GEN-LAST:event_txtForeRActionPerformed

    private void txtForeRKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtForeRKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtForeRKeyPressed

    private void txtForeRKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtForeRKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtForeRKeyReleased

    private void txtThighRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThighRActionPerformed
        txtCalfL.requestFocus();
    }//GEN-LAST:event_txtThighRActionPerformed

    private void txtThighRKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtThighRKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThighRKeyPressed

    private void txtThighRKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtThighRKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThighRKeyReleased

    private void txtCalfRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCalfRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCalfRActionPerformed

    private void txtCalfRKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCalfRKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCalfRKeyPressed

    private void txtCalfRKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCalfRKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCalfRKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbMemberID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCalfL;
    private javax.swing.JTextField txtCalfR;
    private javax.swing.JTextField txtChest;
    private javax.swing.JTextField txtForeL;
    private javax.swing.JTextField txtForeR;
    private javax.swing.JTextField txtHips;
    private javax.swing.JTextField txtMemberName;
    private javax.swing.JTextField txtNeck;
    private javax.swing.JTextField txtShoulder;
    private javax.swing.JTextField txtThighL;
    private javax.swing.JTextField txtThighR;
    private javax.swing.JTextField txtUpperL;
    private javax.swing.JTextField txtUpperR;
    private javax.swing.JTextField txtWaist;
    // End of variables declaration//GEN-END:variables

    private void loadAllMemberID() {
        try {
            ArrayList<MemeberDTO> mList = MemberController.getAllMember();
            for (MemeberDTO memeberDTO : mList) {
                cmbMemberID.addItem(memeberDTO.getMemberID());
            }
        } catch (Exception ex) {
            Logger.getLogger(ViewMeasurmentPanel1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void searchMember() {
        if( cmbMemberID.getSelectedItem()==null){return;}
        String mId = cmbMemberID.getSelectedItem().toString();
        try {
            MemeberDTO memeberDTO = MemberController.searchMember(mId);
            if (memeberDTO != null) {
                txtMemberName.setText(memeberDTO.getMemberName());
                MeasurementDTO measurementDTO=MeasurementController.searchMeasurement(mId);
                if (measurementDTO!=null) {
                    txtNeck.setText(Double.toString(measurementDTO.getNeck()));
                    txtShoulder.setText(Double.toString(measurementDTO.getShoulders()));
                    txtChest.setText(Double.toString(measurementDTO.getChest()));
                    txtWaist.setText(Double.toString(measurementDTO.getWaist()));
                    txtHips.setText(Double.toString(measurementDTO.getHips()));
                    txtUpperL.setText(Double.toString(measurementDTO.getUpperArmLeft()));
                    txtUpperR.setText(Double.toString(measurementDTO.getUpperArmRight()));
                    txtForeL.setText(Double.toString(measurementDTO.getForearmLeft()));
                    txtForeR.setText(Double.toString(measurementDTO.getForearmRight()));
                    txtThighL.setText(Double.toString(measurementDTO.getThighLeft()));
                    txtThighR.setText(Double.toString(measurementDTO.getThighRight()));
                    txtCalfL.setText(Double.toString(measurementDTO.getCalfLeft()));
                    txtCalfR.setText(Double.toString(measurementDTO.getCalfRight()));
                    
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(ViewMeasurmentPanel1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
