/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.mygymmanagement.view.panel;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import lk.ijse.mygymmanagement.controller.MemberController;
import lk.ijse.mygymmanagementsystem.core.dto.MemeberDTO;
import lk.ijse.mygymmanagementsystem.view.HomePage;

/**
 *
 * @author Chinthaka
 */
public class ViewMembersPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public ViewMembersPanel() {
        initComponents();
        getMembers();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMember = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtCount = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(970, 570));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Stencil Std", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("view members..");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 260, 50);

        lblBack.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblBack.setForeground(new java.awt.Color(255, 255, 255));
        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/back.png"))); // NOI18N
        lblBack.setText("BACK");
        lblBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });
        add(lblBack);
        lblBack.setBounds(840, 10, 120, 50);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("All Members");
        add(jLabel4);
        jLabel4.setBounds(350, 100, 240, 40);

        tblMember.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblMember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "        Member ID", "                        Member Name", "           Member NIC", "          Member Tele.No", "                Age"
            }
        ));
        jScrollPane1.setViewportView(tblMember);
        if (tblMember.getColumnModel().getColumnCount() > 0) {
            tblMember.getColumnModel().getColumn(1).setMinWidth(250);
            tblMember.getColumnModel().getColumn(1).setPreferredWidth(250);
            tblMember.getColumnModel().getColumn(1).setMaxWidth(250);
        }

        add(jScrollPane1);
        jScrollPane1.setBounds(80, 160, 780, 310);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Count of All Members :-");
        add(jLabel5);
        jLabel5.setBounds(80, 490, 180, 20);

        txtCount.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtCount.setForeground(new java.awt.Color(255, 255, 255));
        txtCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCount.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        add(txtCount);
        txtCount.setBounds(270, 490, 50, 20);

        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(255, 153, 51), new java.awt.Color(255, 153, 51), new java.awt.Color(255, 153, 51), new java.awt.Color(255, 153, 51)));
        add(jLabel3);
        jLabel3.setBounds(20, 70, 910, 490);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/mygymmanagementsystem/image/Untitled-1.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 3));
        add(jLabel1);
        jLabel1.setBounds(0, 0, 970, 570);
    }// </editor-fold>//GEN-END:initComponents

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        ManageMemberPanel manageMemberPanel = new ManageMemberPanel();
        JPanel middlePanel = HomePage.getMainPanel();
        middlePanel.removeAll();
        manageMemberPanel.setSize(middlePanel.getSize());
        middlePanel.add(manageMemberPanel);
        middlePanel.revalidate();
        middlePanel.repaint();
    }//GEN-LAST:event_lblBackMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBack;
    private javax.swing.JTable tblMember;
    private javax.swing.JLabel txtCount;
    // End of variables declaration//GEN-END:variables

    public void getMembers() {
        ArrayList<MemeberDTO> members;
        try {
            members = MemberController.getAllMember();
            if (members == null) {
                return;
            }
            DefaultTableModel dtm = (DefaultTableModel) tblMember.getModel();
            for (MemeberDTO member : members) {
                Object[] rawData = {member.getMemberID(), member.getMemberName(), member.getNic(), member.getPhoneNo(), member.getAge()};
                dtm.addRow(rawData);
            }
            txtCount.setText(Integer.toString(tblMember.getRowCount()));
        } catch (Exception ex) {
            Logger.getLogger(ViewMembersPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
}
